codegen/golang.go

By always generating a path resolver, we can eliminate uncertainty about what the original field name was.

feat: Always generate path resolver

---

codegen/golang.go
codegen/golang_test.go

This: 
- fixes the test so that it makes assertions (previously it was only printing)
- fixes the test that would have been failing after https://github.com/cloudquery/plugin-sdk/pull/14 if it had been making assertions
- fixes the case where a pointer to time.Time is given. I thought it was working before because I thought the test was making assertions, but it wasn't 😅 
I spent a few minutes trying to make it work with typecasts like before, but couldn't figure out how to get the actual interface from the reflect value after calling `Elem()` to dereference the pointer. Switched to a comparison with `PkgPath` and `Name` instead to save some time, but maybe we can revisit this again later.

fix: NewTableFromStruct pointer to time.Time

---

helpers/slice.go
helpers/slice_test.go

Handles cases when structure has fields that are pointers to slices like `*[]SomeStruct`
---

fix: Pointers to slice are handled correctly

---

go.mod
go.sum
plugins/source.go
schema/table.go
serve/serve.go

plugin developers will be able to direct their plugin errors
to their own projects on sentry as we dont want to monitor any
community errors anyway.
Also each plugin should go into it's own project on sentry
because we are using server side grouping which are mostly
project based.
Tested it on gcp - grouping works smoothly with nice title (no more diags.Error) for every single error as we use standard `sentry.Message` as well as using sentry mechanism to group and change title based on tags.
Every error in the ETL process which is not ignore is sent with the error as string + `table_name` as tag.
https://sentry.io/organizations/cloudquery-v2/issues/?project=6720365
hopefully this brings sane error monitoring one step closer :) 🚀 
---
Use the following steps to ensure your PR is ready to …

feat: Add sentry for serve.Serve function

---

codegen/table.go
schema/table.go

I was using this option to set the primary keys on my tables:
https://github.com/erezrokah/cloudquery/blob/28f7db10eadd834769663dc1e8243f04469b0132/plugins/source/azure/codegen/recipes/base.go#L206
to realize it stopped working and I should set it on columns instead
---

feat!: Remove unused table create options

---

specs/spec_reader.go

So that we can put the config in cli/ and not worry about .golangci.yml.

fix: Ignore hidden files

---

.golangci.yml

Some plugins are no longer supported and can be removed. I am also proposing we remove decorder: until it has the ability to automatically fix the issues it reports, we are wasting our time for (imo) little gain.
As for the deprecated plugins, here is the message from latest golanci-lint:
```
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
```

chore: Golangci: remove deprecated plugins (and decorder)

---

codegen/.snapshots/TestGenerateTemplate-should_add_comma_between_relations
codegen/golang_test.go
codegen/templates/table.go.tpl
go.mod
go.sum

The `TableDefinition.Relations` accepts a string array but it's a bit confusing to use when you have multiple relations as it doesn't add a comma between relations.
As a result if someone has multiple relations they need to work around the issue by doing either:
- `relations:          []string{"siteAuthSettings(),publishingProfiles(),vnetConnections(),publishingProfiles()"}` (a single string) ([code](https://github.com/erezrokah/cloudquery/blob/1bac8634602c4db2e2cb5d8206f8a92aea6052c4/plugins/source/azure/codegen/recipes/web.go#L29))
or 
- `relations:          []string{"siteAuthSettings(),",  "publishingProfiles(),"}`
This PR fixes the issue (this makes the code consistent with [how we template columns](https://github.com/cloudquery/plugin-sdk/blob/e40466ba450499540a02737ace6655ea184fe42e/ …

fix: Add missing comma when generating relations

---

.golangci.yml
faker/faker.go

Fixes the following issue:
`exported: type name will be used as faker.FakerOption by other packages, and that stutters; consider calling this Option (revive)`
---

fix!: Enable export lin rule and fix option export

---

docs/.snapshots/TestGenerateSourcePluginDocs-relation_table.md
docs/.snapshots/TestGenerateSourcePluginDocs-test_table.md
docs/source.go
docs/source_test.go

We don't generate the descriptions anymore (I think), so we should not generate them with the docs.
Also switched to snapshot testing so the output files are separated from the code.
Another possible implementation is to add an option to enable/disable the description column
---

fix: Remove description from docs

---

serve/serve.go

Given that plugins only have `doc, help, serve` commands looks like we can disable the built in completion one
---

feat!: Disable default completion command

---

Makefile

`make gen-proto` requires quite a few dependencies to be installed.
This PR ensures those get installed before running the target (tested on MacOS, not sure what do do on Windows).
More information in https://grpc.io/docs/protoc-installation/
---

chore(makefile): Install protoc dependecies

---

codegen/golang.go
codegen/table.go

reading comments from source code is super slow and this is public api which we dont want to support. The best practice/guideline should be just pointing to the original API and not duplicating go documentation to our docs.
---

feat: Remove withComment for codegen

---

plugins/source.go
plugins/source_test.go

It took me a bit of time to understand what's the purpose of this function as it uses negated logic and also `len(tables) > 1` hides the equality check.
Did a bit of refactoring to make it easier (I hope) to understand and added tests for it
---

chore(refactor): Make `interpolateAllResources` more readable

---

codegen/golang.go

This makes it a bit easier to find which table is being referenced when running codegen.

fix: Improve error message on codegen field error

---

README.md
clients/doc.go
clients/source.go
codegen/doc.go
codegen/golang.go
plugins/docs.go
plugins/source.go
schema/doc.go
serve/doc.go
specs/doc.go
specs/source.go

As part of the v2 release we want to improve documentation for developers and for our plugin-sdk. 
Right now we have a bit of mix-match of tutorials and docs https://www.cloudquery.io/docs/developers/sdk/provider/configuration
What we want to achieve:
- SDK documentation in godoc together with docs - https://pkg.go.dev/github.com/cloudquery/plugin-sdk
- Tutorials - https://www.cloudquery.io/docs/developers/sdk/overview
There is still much more documentation to be added with some more examples but this should be a good start.
---

chore(docs): Add more godoc to important APIs

---

schema/table.go

feat: Add Multiplexer function type

---

plugins/.snapshots/TestGenerateSourcePluginDocs-relation_table.md
plugins/.snapshots/TestGenerateSourcePluginDocs-test_table.md
plugins/source_docs.go
plugins/source_docs_test.go

This is important information to have, as it will tell users what columns will be used for replacing rows in overwrite mode, as well as inform on good candidates for performing relational joins.

feat: Add PK information to generated docs

---

codegen/golang.go
codegen/golang_test.go

If field has a `json: "-"` tag that means that it is not the data parsed from api. so such a field should be skipped.
---

fix: Skip fields that have "-" json tag

---

serve/destination.go
serve/source.go

fix: Use plugin name to print usage

---

plugins/.snapshots/TestGenerateSourcePluginDocs-README.md
plugins/.snapshots/TestGenerateSourcePluginDocs-relation_table.md
plugins/.snapshots/TestGenerateSourcePluginDocs-test_table.md
plugins/source.go
plugins/source_docs.go
plugins/templates/all_tables.go.tpl
plugins/templates/table.go.tpl

This adds a `Relations` section to generated docs, with information about parent- and child relationships. 
For example, a parent table might look like this:
```
The following tables depend on `aws_accessanalyzer_analyzers`:
- [`aws_accessanalyzer_analyzer_findings`](aws_accessanalyzer_analyzer_findings.md)
- [`aws_accessanalyzer_analyzer_archive_rules`](aws_accessanalyzer_analyzer_archive_rules.md)
```
And a child table will look like this:
```
This table depends on [`aws_accessanalyzer_analyzers`](aws_accessanalyzer_analyzers.md).
```

feat: Add information about relations to generated docs

---

plugins/source_testing.go

This catches a new class of bug where an already-marshalled string or byte-slice gets passed to a JSON column. This results in string that gets doubly-marshalled, which is not the intention. Instead, either the unmarshalled object should be passed in, or the column type should be changed to string.

feat: Test that JSON columns don't receive string values

---

codegen/table.go
codegen/table_test.go

https://github.com/cloudquery/plugin-sdk/pull/157 changed the behavior of printing a log message on unsupported types (like `interface`) to failing.
~~I'm not sure that's what we want as now the consumer has to skip all the interface fields to make code gen work.~~
~~I kept the failure on custom type transformer as I believe that should be indeed a failure to generate.~~
Changed the code to explicitly specific types
---

feat: Ignore specific field types

---

schema/resolvers.go

Related to https://github.com/cloudquery/plugin-sdk/issues/199, I think we can (and should) use `ParentResourceFieldResolver` instead as it operates on the post processed table data of the parent, instead of the pre-processed data of the struct.
---

feat!: Remove ParentPathResolver

---

clients/destination.go
clients/destination_test.go
clients/download.go
clients/source.go
clients/source_test.go
serve/destination.go
serve/destination_test.go
serve/serve.go
serve/source.go
serve/source_test.go

I think I finally nailed the Client interface. This will remove completely the need for "PluginManager" in the CLI and yet another abstraction layer and prop drilling with WithOptions duplicates for every abstraction layer.
Also, the SDK is aware of `registry`, `path` and `version` so I really think it should be here. it turns the CLI intro real CLI finally.

feat: Make NewSourceClient (and dest) as one interface

---

plugins/source_docs.go

I couldn't find where this template function is being used
---

fix: Remove unused docs template function

---

clients/download.go

Hard to test this as we need to release a new SDK, update it in the CLI and then test again via https://github.com/cloudquery/cloudquery/pull/2204.
Similar to the fix in https://github.com/cloudquery/cloudquery/pull/1894
---

fix: Use correct path for Windows zip

---

plugins/source_docs.go

If you run the `doc` command and the output directory doesn't exist, the command will fail. This fixes it
---

fix: Create doc directory if doesn't exist

---

clients/destination.go

Destinations are being downloaded to `plugins/source/*` at the moment
---

fix: Download destinations to 'destination' directory

---

clients/destination.go
clients/download.go
clients/source.go

Currently plugins are downloaded to `CWD/plugins/*`. This PR changes it so they are downloaded to `CWD/.cq/plugins/*`
---

fix: Set default download directory to `.cq`

---

clients/destination.go
clients/download.go
clients/source.go

Based on `go` source code binaries on Windows must end in `exe`, `cmd`, etc. See https://github.com/golang/go/blob/f6d844510d5f1e3b3098eba255d9b633d45eac3b/src/os/exec/lp_windows.go#L39
⬆️ Is the code that looks up the binary when you use the `exec` package
---

fix: Use correct binary path on Windows

---

clients/destination.go
clients/download.go
clients/random.go
clients/source.go

closes #245 
`grpc.Dial` does not work with "unix://" prefix on windows. protocol should be set in dialer to make it work
---

fix: Plugin connection using Unix Domain Socket fixed for windows

---

clients/download.go

This PR and this https://github.com/cloudquery/cloudquery/pull/2459 should ensure logs and stdout are not running over each other.
The convention should be the following fmt.Print* -> stdout, logs -> stderr
this way it's easy to turn off one stream or the other depending on the need

fix: Progressbar should go into stdout

---

schema/table.go

If we continue the resolving after PreRR error, more (this time type based) errors are generated from the column resolvers that expect a certain type.

fix: Stop if PreResourceResolver fails

---

schema/table.go
schema/table_test.go

This also adds quite needed tests for our scheduler

fix: Recover panic in table resolver and object resolver flows

---

.github/workflows/release-pr.yml

This is a small optimization to how we do SDK updates in the monorepo. At the moment renovate runs every 15 minutes to handle dependencies updates. We run it every 15 minutes to ensure speedy updates to the SDK.
With this PR we'll run it immediately after the SDK has been released.
This should also allow us to save some build minuted by reducing the renovate schedule to 1 hour for example
---

chore(ci): Trigger renovate after SDK release

---

clients/destination.go
clients/log_reader.go
clients/log_reader_test.go
clients/source.go

This fixes an issue where the CLI would hang indefinitely when it encountered a log line from a plugin that was longer than the buffer size allowed for by `bufio.Scanner`. The fix uses a wrapper around `bufio.NewReader` to skip lines that are too long to be parsed, printing an error in the log with the first 1000 characters to help with identification.

fix: Add custom log reader implementation to fix hang on long log lines

---

plugins/.snapshots/TestGenerateSourcePluginDocs-relation_table.md
plugins/.snapshots/TestGenerateSourcePluginDocs-test_table.md
plugins/destination.go
plugins/source.go
plugins/source_docs.go
schema/meta.go
schema/table.go

testing matrix (two syncs, different versions for first and second sync )
---

fix: DeleteStale feature

---

serve/destination.go
serve/source.go

Same as https://github.com/cloudquery/plugin-sdk/pull/273 but for source plugins

fix: Ignore sentry in development, case-insensitive for source plugins

---

specs/source.go

This makes https://github.com/cloudquery/plugin-sdk/pull/268 backwards-compatible with prior versions, as support for `concurrency` is retained for now.

fix: Make concurrency change backwards-compatible

---

internal/servers/source.go

See https://github.com/cloudquery/cloudquery/issues/2612 for an explanation.
Notes:
- We weren't using `DisallowUnknownFields` on the destination plugin side
- We don't currently have a mechanism to warn about unknown fields, but we are working on it https://github.com/cloudquery/plugin-sdk/pull/272
- This will unfortunately not fix plugins that have already been released. Our next CLI release that adds new fields will have to be breaking, but after that they can be backwards-compatible.

fix: Remove DisallowUnknownFields from Source plugin server

---

schema/table.go

We were missing a `Release` call on the `resource_concurrency` semaphore.

fix: Call Release on resource semaphore

---

plugins/.snapshots/TestGenerateSourcePluginDocs-README.md
plugins/.snapshots/TestGenerateSourcePluginDocs-test_table.md
plugins/source_docs_test.go
plugins/templates/all_tables.go.tpl

This updates the README for table docs in two ways:
- links to the table (right now when you land on [this page](https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/docs/tables/README.md) for example, there's no indication that there is actually more information)
- adds information about relations, if any
I'm happy to take suggestions about how to better present these; I just think it's important we improve the discoverability a little bit now and keep making incremental improvements afterwards.

feat: Add links to tables in table README.md, and list of relations

---

clients/source.go

Follow up to https://github.com/cloudquery/plugin-sdk/pull/294
---

fix: Use 'source' in error message instead of 'destination'

---

plugins/.snapshots/TestGenerateSourcePluginDocs-README.md
plugins/.snapshots/TestGenerateSourcePluginDocs-relation_table.md
plugins/.snapshots/TestGenerateSourcePluginDocs-test_table.md
plugins/templates/all_tables.go.tpl
plugins/templates/table.go.tpl

Descriptions are too detailed for the summary table, and are removed in this PR. 
I'm also changing the format of the table a little bit: instead of having child tables in a separate column, I'm experimenting with having them in their own rows but indicated as a child table with an arrow. Not sure this will be the final version, but I think it looks a bit better than what we had before.

fix: Remove descriptions from table docs

---

plugins/source.go
plugins/source_test.go
schema/resolvers_test.go
schema/table.go
schema/table_test.go

This sets expectations for table and column names (currently enforced only through convention) that ensure we don't accidentally add resources with invalid table or column names.
Closes https://github.com/cloudquery/plugin-sdk/issues/255

feat: Validate source plugin table and column names

---

serve/destination.go
serve/source.go

Sentry [does not consider server name PII](https://forum.sentry.io/t/sentry-python-sdk-dont-send-server-name/5815/2), as it's not a unique identifier, but we'd rather have our data be fully anonymous.

fix: Set Sentry server name to empty to avoid sending it

---

go.mod
go.sum

Fixes https://github.com/cloudquery/cloudquery-issues/issues/452 (internal issue) by updating `go-funk` to a version that includes the fix from https://github.com/thoas/go-funk/pull/159
> I used `go get github.com/thoas/go-funk@5573bc209e28c4202e955474c0a24ca35da80989` to update as my PR was merged but not released as a tag ([hopefully coming soon](https://github.com/thoas/go-funk/pull/159#issuecomment-1293344570)).
---

fix(deps): Update go-funk

---

go.mod
go.sum

This reverts commit fea5c2855d46d1cefacb9ed826dc78dfad45a6f7.
This PR reverts the `go-funk` update as it's causing some issues in our CI:
https://github.com/cloudquery/cloudquery/actions/runs/3337210255/jobs/5523265480#step:7:78
---

fix: Revert "fix(deps): Update go-funk (#312)"

---

plugins/source.go
plugins/source_validate.go
plugins/source_validate_test.go

Previously this didn't work because `p.tables` does not contain child tables.

fix: Check for missing parent tables

---

specs/spec_reader.go
specs/spec_reader_test.go
specs/testdata/multiple_sources.yml

Fixes https://github.com/cloudquery/plugin-sdk/issues/350
---

fix: Include source path in dest to source map key

---

plugins/destination_reverse_transformer.go

There is no need for reflection in reverse transformer as it's already an array.

fix: Dont use reflection in reverse transformer

---

plugins/source_test.go
serve/source_test.go
specs/destination.go
specs/destination_test.go
specs/source.go
specs/source_test.go
specs/testdata/multiple_sources.yml

This updates (and replaces) this earlier PR for making `path` a required config parameter: https://github.com/cloudquery/plugin-sdk/pull/265
We have received numerous user reports of the distinction between name and path being confusing, so rather than infer path from name in some circumstances (and not in some others), this change makes things consistent by always requiring both. I've also added a small hint for users running into this error when upgrading from earlier versions.
We will not consider this a breaking SDK change, as it doesn't change any protocols, but it will be a breaking CLI change.
- relates to https://github.com/cloudquery/plugin-sdk/issues/317 
- closes https://github.com/cloudquery/plugin-sdk/issues/256

fix: Make path a required config parameter

---

clients/destination.go
clients/source.go
plugins/destination.go

This is a fix for this error, encountered when postgresql plugin is run with overwrite-delete-stale mode:
```
Error: failed to write for gcp->postgresql: failed to CloseAndRecv client: rpc error: code = Canceled desc = got EOF. failed to wait for plugin: failed to execute batch: context canceled
2022-11-09T10:11:35Z ERR exiting with error error="failed to write for gcp->postgresql: failed to CloseAndRecv client: rpc error: code = Canceled desc = got EOF. failed to wait for plugin: failed to execute batch: context canceled" module=cli
```
The reason it didn't work before is that the grouperr context gets cancelled as soon as Wait() returns. We should be using the original `ctx` for the subsequent delete stale call.
This also fixes this error:
```
2022-11-09T10:02:22Z ERR failed to remove …
```

fix: Context cancelled too early for delete stale mode

---

faker/faker.go
schema/timestamptz_test.go

Fixes https://github.com/cloudquery/cloudquery/issues/3627.
**The TLDR** is that we should `MarshalText` when faking time data, as that follows an RFC.
**The DON'T READ part is**:
If we don't do it and default to `String()` that sometimes creates a string that cannot be parsed by `const defaultStringFormat = "2006-01-02 15:04:05.999999999 -0700 MST"`.
You can see an example in https://github.com/cloudquery/cloudquery/issues/3627 that the `2110-10-19 08:53:50.21670207 +0000 UTC m=+2775422040.494306874` string was created.
The reason that the string can't be parsed is because the nano seconds part has 8 digits and not 9, that is `21670207` instead of `216702070`.
The nano seconds string needs to be padded only when adding the `m=+2775422040.494306874` part. This was added in go 1.19 (see …

fix(faker): Use `MarshalText` for faker timestamps

---

faker/faker.go
faker/faker_test.go
schema/timestamptz_test.go

This reverts commit a29143861b22432c81cdc8b04650d9d8d0ac9671.
Reverts https://github.com/cloudquery/plugin-sdk/issues/373 as I applied that fix in the wrong place. I think the fix should be where we serialize/deserialize `time.time`
---

fix: Revert "fix(faker): Use `MarshalText` for faker timestamps (#373)"

---

plugins/source_scheduler_dfs.go

Fixes https://github.com/cloudquery/plugin-sdk/issues/374.
We can start with 10 minutes to unblock users, and can make it configurable in the future
---

fix: Update `resolveResource` timeout to 10 minutes

---

schema/timestamptz.go
schema/timestamptz_test.go

Proper fix for https://github.com/cloudquery/plugin-sdk/pull/373
---

fix: Use MarshalText when serializing timestamps when applicable

---

internal/servers/source.go
serve/source_test.go

This is a short-term fix for https://github.com/cloudquery/cloudquery/issues/3962 while we work on a better solution. It pre-aggregates metric results before sending it from the server, so that only a small map gets sent over the wire. We can do this because we know the CloudQuery CLI right now only makes use of the aggregated data in any case.

fix: Pre-aggregate metrics before sending

---

plugins/source_validate.go
plugins/source_validate_test.go
schema/table.go

Follow-up to https://github.com/cloudquery/plugin-sdk/pull/398 to ensure that all descendants of a parent table are added (or skipped) by default. This makes it a non-breaking change.

fix: Change globbing behavior to include descendants by default

---

plugins/destination_test.go
plugins/destination_testing.go

Seems we weren't running some tests. I had to invert the variables which actually also make sense so they will be enabled by default. Let's say we add a new test this will detect if a plugin is not supporting a new mode.

fix: Fix Destination testing suite

---

plugins/benchmark_test.go
plugins/source_test.go

This adds a source plugin benchmark that runs in-memory. It allows for different scenarios to be set up, but currently comes with only two: one scenario without child tables, and one with child tables. 
Here are the results on my machine:
```
BenchmarkDefaultConcurrency
BenchmarkDefaultConcurrency-8                     	       1	     11637 resources/s	     12626 targetResources/s	73510696 B/op	 1032412 allocs/op
BenchmarkTablesWithChildrenDefaultConcurrency
BenchmarkTablesWithChildrenDefaultConcurrency-8   	       1	       544.6 resources/s	     40606 targetResources/s	461292456 B/op	 6689992 allocs/op
PASS
```
The output is different from normal Go benchmarks, and I feel it better fits our use-case. It shows the actual `resources/s`, similar to what the CLI would show. It also shows a …

chore: Add source plugin benchmark

---

specs/spec_reader.go
specs/spec_reader_test.go
specs/testdata/creds.txt
specs/testdata/creds1.txt
specs/testdata/gcp.yml

Per user request. we had a similar version of that in v0 but now it is generic and available to all specs and not only to a specific destination.

feat: Support ${file:./path} expansion in spec

---

clients/constants.go
clients/destination.go
clients/source.go
serve/constants.go
serve/destination.go
serve/source.go

The default was 4MiB, and users have reported running into this limit on occasion. If 50MiB isn't enough, we'll probably need to implement some logic to drop messages at that point since they'll be too big to be useful for many databases anyway. Let's see if increasing the limit to 50MiB solves the problem first though.
https://github.com/cloudquery/cloudquery/issues/4834

fix: Increase GRPC message size limit to 50MiB

---

plugins/source.go
plugins/source_scheduler_dfs.go

This changes the resolver for table relations to work concurrently, like parent tables. To do so safely and without the risk of deadlock, we instantiate one semaphore per depth level. (The size of the semaphore is decreased logarithmically for each depth.)
This change will only improve performance for tables with child relations.
To compare the performance before and after, I used the benchmarks in https://github.com/cloudquery/plugin-sdk/pull/415
```
goos: darwin
goarch: arm64
pkg: github.com/cloudquery/plugin-sdk/plugins
BenchmarkDefaultConcurrency-8                     	       1	     11957 resources/s	     12626 targetResources/s	73597280 B/op	 1032425 allocs/op
BenchmarkTablesWithChildrenDefaultConcurrency-8   	       1	       545.9 resources/s	     40606 targetResources/s	461622584 …
```

feat: Resolve table relations in parallel

---

plugins/source.go
plugins/source_scheduler_dfs.go

Reverts cloudquery/plugin-sdk#416
Nothing wrong with it as far as we know, but we want to release it separately from https://github.com/cloudquery/plugin-sdk/pull/421

fix: Revert "feat: Resolve table relations in parallel"

---

.github/workflows/unittest.yml
.gitignore
Makefile
scripts/benchmark-delta/main.go

Adds a Github Action step to run benchmarks in CI and report on the differences with `main`.
It uses a combination of [gobenchdata](https://github.com/bobheadxi/gobenchdata), the [netlify/delta-action](https://github.com/netlify/delta-action) and a simple Go script to glue them together.
Example from lower down in this PR:
Closes https://github.com/cloudquery/plugin-sdk/issues/424

chore: Run benchmarks in CI

---

.github/workflows/unittest.yml

We need slightly elevated permissions to make a comment when the PR comes from a fork, and I believe this should do the trick.
Github Actions security when it comes to external PRs is a bit of a minefield, but because we're avoiding the `pull_request_target` trigger here, and not running any repository code in the delta-action itself, I believe this is safe.
This should fix the issue we're seeing here https://github.com/cloudquery/plugin-sdk/pull/430

chore: Use GH_CQ_BOT token to comment on Benchmark results

---

.github/workflows/unittest.yml

The fix in https://github.com/cloudquery/plugin-sdk/pull/436 didn't work; looks like you can't use the GH bot token from a forked repo PR either.

chore: Remove benchmark comments for now

---

plugins/.snapshots/TestGenerateSourcePluginDocs-JSON-__tables.json
plugins/.snapshots/TestGenerateSourcePluginDocs-Markdown-README.md
plugins/.snapshots/TestGenerateSourcePluginDocs-Markdown-relation_relation_table.md
plugins/.snapshots/TestGenerateSourcePluginDocs-Markdown-relation_table.md
plugins/.snapshots/TestGenerateSourcePluginDocs-Markdown-test_table.md
plugins/source_docs.go
plugins/source_docs_test.go
plugins/templates/all_tables.md.go.tpl
plugins/templates/all_tables_entry.md.go.tpl
plugins/templates/table.md.go.tpl

Closes https://github.com/cloudquery/plugin-sdk/issues/428

fix: Fix docs for deeply nested tables

---

schema/json.go
schema/json_test.go

In fields like 'Tags', 'Annotations' - it is more consistent if empty/null dictionaries show up as an empty JSON object `{}`, rather than being a postgres "null" or a JSON "null".
---

feat: Handle resolving of empty maps and slices

---

.github/workflows/unittest-post.yml
.github/workflows/unittest.yml

Brings back the benchmark comment based on https://github.com/cloudquery/plugin-sdk/pull/437#issuecomment-1329194054
This should only start working post merge (I hope) as the workflow file needs to be on the `main` branch
---

chore(ci): Bring back benchmark comment

---

.github/workflows/unittest.yml

Follow up to https://github.com/cloudquery/plugin-sdk/pull/441. We should only upload the results when running on Ubuntu
---

chore(ci): Upload benchmark results only for ubuntu

---

plugins/source_scheduler_dfs.go

Related to: https://github.com/cloudquery/cloudquery/issues/5273
Logging every start and finish of relational tables fetches, means that the number of logs depends on the number of [parent] resources.
for example, logs for fetching `aws_rds_*` (where there are many `aws_rds_engine_versions` resources, with `aws_rds_cluster_parameters` relations).
All the relational-fetch logs are identical:
```
2022-12-03T09:00:19Z INF fetch table finished client=615713231484:eu-north-1 errors=0 module=aws-src resources=5576 table=aws_rds_cluster_parameters
2022-12-03T09:00:19Z INF table resolver started client=615713231484:eu-north-1 module=aws-src table=aws_rds_cluster_parameters
2022-12-03T09:00:19Z INF fetch table finished client=615713231484:eu-north-1 errors=0 module=aws-src resources=5576 …
```

fix: Don't log start-and-finish of relational tables

---

plugins/source.go
plugins/source_test.go

Related to https://github.com/cloudquery/cloudquery/pull/5294

fix: TablesForSpec should only return top-level tables

---

faker/faker.go
faker/faker_test.go

The Gitlab Plugin I am working on has `net.IP` fields... existing implementation does not produce a valid IP address so needs explicit support
---

feat: Add Support for net.IP in Faker

---

plugins/source_metrics.go

Prior to this change resource, error, and panic count were only reset when a plugin was relaunched. This means if a plugin is being run via direct gRPC calls then the summary was a total of all of the runs.
This PR reinitializes the metrics for each sync
---

fix: Sync Metrics for Long running plugins

---

codegen/table_test.go
codegen/transformers.go

* `[]*string` will become `schema.TypeStringArray`
* `[]*int(8|16|32|64)` will become `schema.TypeIntArray`
---

fix(codegen)!: Column type for slices

---

plugins/source.go
plugins/source_metrics.go
plugins/source_scheduler_dfs.go
plugins/source_test.go

This fix a panic that was caused if plugins misbehave and return difference results for difference runs with the same config.

fix: Initialise clients only once

---

faker/faker.go
faker/faker_test.go

When faking data, it is useful if `json.Number` is faked with a number, otherwise json marshalling fails later with `"test string" is not a number`.

feat: Add handling for json.Number in faker

---

specs/spec_reader.go
specs/spec_reader_test.go
specs/testdata/dir_yaml/aws.yaml
specs/testdata/dir_yaml/postgresql.yaml

Fixes: https://github.com/cloudquery/cloudquery/issues/5502
---

fix: Allow both 'yml' and 'yaml' extensions

---

internal/servers/source.go

Related to https://github.com/cloudquery/plugin-sdk/issues/462 and also https://github.com/cloudquery/plugin-sdk/pull/477.
Two reasons for this change:
1. We shouldn't be using `codes.Internal` as it's generated internally by gRPC so we won't be able to distinguish between gRPC protocol errors and application level errors, see https://github.com/grpc/grpc-go/blob/eeb9afa1f6b6388152955eeca8926e36ca94c768/codes/codes.go#L166.
2. We don't really do anything with the code at the moment, it's only printed in a confusing way (see https://github.com/cloudquery/plugin-sdk/pull/477)
---

fix(errors): Remove usage of `codes.Internal`

---

specs/source.go

When plugins have many tables, like the new Azure plugin we quickly run into memory issues with the current default.
This works on my machine ™️ with the new Azure plugin
---

fix: Reduce default concurrency

---

schema/table.go
schema/table_test.go

If parent is selected all child selected as well unless explicitly skipped.

fix: Glob table filtering

---

plugins/source/scheduler_dfs.go

currently we silently drop metrics from child tables. This add them back when root table sync is finished so it is printed once per table/client (and not per object like it was before with millions of log lines)

fix: Add better logging/metric per table

---

plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-README.md
plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-relation_relation_table.md
plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-relation_table.md
plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-test_table.md
plugins/source/docs.go

This neatens the newlines rendered for table docs, so we can no longer get multiple newlines in a row, like here: https://github.com/cloudquery/cloudquery/pull/5547/files#diff-7a51ae50d93ba1ae94ee3a2e3ff898ae0224a0a1cc32cafe0c667ff46cf080e6R1-R8
Closes https://github.com/cloudquery/plugin-sdk/issues/454

fix: Improve formatting of newlines in markdown files

---

.github/workflows/lint_golang.yml

I think this should fix the `interface{}/any` check

chore(ci): Upgrade golangci-lint to v1.50.1

---

plugins/destination/managed_writer.go

Related to https://github.com/cloudquery/cloudquery/issues/6070. This fixes a deadlock in the managed writer when we wait for the flush to finish indefinitely.
The cause is that the resources can already be flushed by another case in the switch, so there might not be resources to flush when we hit the flush case.
The fix is to always pass `done` to the channel 
---

fix(destinations): Set done even if no resources to flush

---

plugins/destination/plugin.go
specs/destination.go
specs/destination_test.go
specs/spec_reader.go

Replaces https://github.com/cloudquery/plugin-sdk/pull/539. Keeps batch size on the top level spec, but allows plugins to override it
---

feat(destinations): Allow plugins to set default batch size

---

transformers/struct.go
transformers/struct_test.go

Follow-up on transformation. Adding unwrap option as needed in some cases where we create our own wrapper struct.
This also moves the tests from codegen.

feat: Add unwrap option to transformations

---

transformers/struct.go

For some plugins it's useful to configure a resolver based on the field's type:
https://github.com/cloudquery/cloudquery/blob/876cc163d6dff277bb09a5147162a8646fcd98de/plugins/source/gcp/codegen/main.go#L263
I don't use the default one from `codegen` package like others as it returns `(string, error)` and we want to return a `schema.ColumnResolver` instead
---

feat: Add WithResolverTransformer

---

internal/memdb/memdb_test.go
plugins/destination/managed_writer.go
plugins/destination/plugin.go
specs/destination.go
specs/destination_test.go
specs/spec_reader.go

This adds `batchSizeBytes` as an additional option to limit batches not only by number of records, but also by number of bytes.

feat: Add batch size bytes as additional option

---

plugins/source/scheduler.go
plugins/source/scheduler_dfs.go
schema/bool.go
schema/bytea.go
schema/cidr_array.go
schema/errors.go
schema/float8.go
schema/inet.go
schema/inet_array.go
schema/int8.go
schema/int8_array.go
schema/json.go
schema/macaddr.go
schema/macaddr_array.go
schema/text.go
schema/text_array.go
schema/timestamptz.go
schema/uuid.go
schema/uuid_array.go

Apparently we weren't really sending anything to sentry (apart from one place in table resolver panics).
Now this should send sentry errors on all panics that we catch + all validation errors.

fix: Sentry errors not sent

---

plugins/source/.snapshots/TestGeneratePluginDocs-JSON-__tables.json
plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-README.md
plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-relation_relation_table_a.md
plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-relation_relation_table_b.md
plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-relation_table.md
plugins/source/docs.go
plugins/source/docs_test.go
plugins/source/templates/all_tables.md.go.tpl

Our docs show tables based on definition order which can be inconsistent and makes it harder to locate a table, see https://www.cloudquery.io/docs/plugins/sources/azure/tables:
This PR sorts the tables and relations before generating the docs
---

feat(docs): Sort tables

---

transformers/struct.go
transformers/struct_test.go

A follow up to https://github.com/cloudquery/cloudquery/pull/6588 where `net.IP` was resolved to `TypeByteArray` by the SDK and we had to manually configure it https://github.com/cloudquery/cloudquery/pull/6588/commits/0ccf23be4b556ad5d6f252cecc9e13df18fa251c
---

feat(transformers): Add support for `net.IP`

---

plugins/source/plugin.go
plugins/source/plugin_test.go

This will only add the default PKs once the `Transformers` have run and added any and all PKs
---

fix: PK Addition Order

---

internal/memdb/memdb_test.go
plugins/destination/plugin.go

We need to pass the correct spec to the client constructor.
Currently, we set defaults on `p.spec`, but pass `spec` that can be not initialized properly.

fix(destination): Pass proper spec to client constructor

---

specs/destination.go
specs/destination_test.go
specs/source.go
specs/source_test.go

A user recently ran into some issues since they thought they used a newer version of a plugin, but actually used an old one.
This PR adds `String()` methods to specs so we can use them in logs/errors.
CLI PR https://github.com/cloudquery/cloudquery/pull/6842
---

feat(spec): Add source, destination String methods

---

clients/destination/v0/destination.go
clients/destination/v0/destination_test.go
clients/source/v0/source.go
clients/source/v0/source_test.go
clients/source/v1/source.go
serve/destination_v0_test.go
serve/source_v0_test.go
serve/source_v1_test.go

Import paths and references will need to be updated after https://github.com/cloudquery/plugin-sdk/pull/610 anyway, let's use this opportunity to change from e.g. `destination.WithDestinationLogger(log.Logger)` to `destination.WithLogger(log.Logger)`
~I will update the tests momentarily...~ done

fix: Simplify client naming conventions

---

clients/destination/v0/destination.go
clients/source/v0/source.go
internal/logging/log_reader.go
internal/logging/log_reader_test.go

Fixes https://github.com/cloudquery/cloudquery/issues/5665, by making this log message look less like an error.
I could go with `Warn` too and maybe update the level of the other errors here (but won't do it unless someone finds those confusing).
The current message can cause users to think that there is data loss or something wrong with the sync
---

fix(clients): Update `log line too long` message

---

specs/spec_reader.go
specs/spec_reader_test.go
specs/testdata/env_variable_in_string.yml
specs/testdata/env_variables.yml

- Fixes https://github.com/cloudquery/plugin-sdk/issues/613
This changes the yaml config parsing code to ignore comments entirely. The solution used here is relatively short and clean, but it required some unfortunate hacking because the curly brackets we use for env variable placeholders are not valid yaml, and so any attempt to parse the yaml with them still in place fails (unless we were to write our own parser). 
Simple regex replacement of comments would also be prone to issues, because it wouldn't be aware of the context (maybe the `#` is inside a string, for example). This solution replaces the variables with temporary placeholders, converts each yaml section to json and back to yaml to strip comments, and then replaces the temporary placeholders again before continuing as before.

fix: Ignore env variables in comments

---

plugins/source/plugin.go

This is more of hot fix/patch to https://github.com/cloudquery/plugin-sdk/pull/610.
https://github.com/cloudquery/plugin-sdk/pull/610 had an unwanted side effect on the migrate command, as now we init the plugin before running it.
initializing the plugin is expensive, requires credentials and does a whole lot of validations, for example:
https://github.com/cloudquery/cloudquery/blob/a06139efad9a2e8de14f186a223222c9d52ce58a/plugins/source/aws/client/client.go#L383
https://github.com/cloudquery/cloudquery/blob/a06139efad9a2e8de14f186a223222c9d52ce58a/plugins/source/azure/client/client.go#L124
Those seem unnecessary for tables migration (unless one uses dynamic tables).
---

fix: Only call `newExecutionClient` if needed

---

internal/pk/pk.go
internal/pk/pk_test.go
plugins/destination/managed_writer.go

feat(destination): Filter the duplicate primary keys prior to writing batch

---

clients/discovery/v0/discovery.go

Reverts cloudquery/plugin-sdk#633
Seems like it wasn't right - we can pass in an option to set the directory instead.

chore: Revert "fix: Add cq-dir param to discovery"

---

registry/download.go
registry/download_test.go

Right now, if a plugin is hosted in anywhere on the `cloudquery` org, it can only be downloaded if it is part of the `cloudquery/cloudquery` monorepo. This makes it impossible to temporarily host `cq-source-*` type plugins as other `cloudquery` repos, as can be done with community plugins on other orgs.
This changes the download logic to first check the monorepo, but fall back to the community standard of `cq-source-*` if it's A) `cloudquery` org and B) the monorepo download attempt resulted in a 404. If both fail with 404, the attempt is aborted. Other status codes are retried.
It would have been better if we could know, somehow, when a plugin is hosted in the monorepo or outside it, but right now this is not possible unless we change the spec in some way. 
This change allows us to use …

feat: Support downloading plugins from other cloudquery repos

---

clients/destination/v0/destination_terminate.go
clients/source/v1/source_terminate.go

Related to https://github.com/cloudquery/cloudquery/issues/6431
This change should inform users if either the source or destination gets killed by the OOM Killer.

fix(logging): Log more explicit message when OOM and other status codes occur

---

serve/destination.go
serve/source.go

This should help debug issues with ECS a bit more effectively, by knowing when the source or destination plugins receive terminate signals.

fix: Trap terminate signal, log which signal we received

---

specs/source.go

This property is no longer necessary (and is unused) - instead, users can update their config to only select the incremental tables they are interested in.

fix: Remove unused `OnlyIncrementalTables` spec property

---

plugins/destination/plugin.go
plugins/source/plugin.go
schema/table.go
schema/table_test.go
specs/source.go

This adds a flag to the source config that allows users to opt out of syncing dependent tables by default. This has been raised as an issue by users a few times already, most recently [here](https://discord.com/channels/872925471417962546/873606591335759872/1071081863105495178). 
The issue with the current default behavior is that new dependencies can be added with minor versions, which can 1) drastically slow down a sync and 2) create unexpected migrations or new tables. It can also be surprising for new users, when selecting e.g. only the `aws_s3_buckets` table, that they get ~6 tables synced.
This should ideally be the default behavior, but that would be a breaking change. For now, I think we should keep backwards-compatibility but add this flag (and recommend it as best-practice). …

feat: Add skip_dependent_tables option

---

plugins/source/testing.go

Enable each individual plugin to pass in any and all additional validator functions they want...
---

feat: Enable Custom Validators

---

clients/destination/v0/destination.go
clients/destination/v0/destination_unix.go
clients/destination/v0/destination_windows.go
clients/source/v1/source.go
clients/source/v1/source_unix.go
clients/source/v1/source_windows.go

By default, commands in Go are started in the same process group. When a signal is sent (e.g. ctrl+c), this gets sent to the entire group, causing plugins to shut down before the CLI has a chance to do closing operations and then relay the signal. By setting `Setpgid: true` on UNIX systems, we can get better control over the shutdown process of child processes.

feat: Use Setpgid=true on Unix systems so that signals are not sent to the child process

---

plugins/destination/plugin_testing.go
plugins/destination/plugin_testing_migrate.go
plugins/destination/plugin_testing_overwrite.go
plugins/destination/plugin_testing_overwrite_delete_stale.go
plugins/destination/plugin_testing_write_append.go
schema/column.go
schema/table.go
schema/table_test.go

fix: Destination testing add force tests

---

plugins/destination/plugin_testing.go
plugins/destination/plugin_testing_migrate.go
plugins/destination/plugin_testing_overwrite.go
plugins/destination/plugin_testing_overwrite_delete_stale.go
plugins/destination/plugin_testing_write_append.go

For each test in the destination testing suite we use unique table now.
This should solve the bug I've hit this PR - https://github.com/cloudquery/cloudquery/pull/7819

fix: Potential database lock/race in destination testing

---

internal/memdb/memdb_test.go
plugins/destination/plugin_testing.go

Follow-up to this - https://github.com/cloudquery/plugin-sdk/pull/678

fix: Take2 of fixing race in destination testing

---

.github/workflows/lint_golang.yml

`--verbose` makes it very hard to see the actual linting issues reported when looking at the GitHub Action workflow logs
---

chore(ci-lint): Remove verbose flag

---

plugins/destination/plugin_testing.go

Quite hard to debug locally https://github.com/cloudquery/cloudquery/pull/7819 so sorry for influx of PRs. 
My current theory is that the db is blocked on number of connections.
The next thing that I might be trying is to not to do those tests concurrently as it can cause weird things in databases and just do those sequentially.

fix: Fix race in dest testing try 3

---

plugins/destination/plugin.go
schema/meta.go
schema/type_test.go

This should solve this https://github.com/cloudquery/cloudquery/pull/7819#pullrequestreview-1295205183 and make sure all logic is the same across all destinations without custom logic per destinatino.

fix: Make sure _cq_id unique across all dest plugins

---

plugins/destination/plugin.go

Have no idea how the `return` got in there 😢

fix: Set _cq_id not null for all tables

---

internal/memdb/memdb.go
internal/memdb/memdb_test.go
plugins/destination/plugin_testing.go
plugins/destination/plugin_testing_migrate.go
schema/column.go
schema/table.go
schema/table_test.go

Migration detection APIs take 2.
- This creates **one** API that returns all the changes instead of multiple growing APIs for different set of changes.
- Improves Migration tests for different use-cases
This will come up also with a Postgres PR and documentation PR:
Basically each destination plugin would have the following table:
Migrations Logic
|  Change  | Behaviour                                        |
|----------|----------------------------------|
|  Add Column | Auto Migrate/Drop Table         | 
|  Add Column with Not Null | Auto Migrate/Drop Table  |  
|  Remove Column | Auto Migrate/Drop Table  |
|  Remove Column with Not Null | Auto Migrate/Drop Table  |
|  Change Column |  Auto Migrate/Drop Table |
and we can easily expand it in the code, tests and documentations.
Example …

feat: Improve migration detection APIs

---

schema/table.go

fix: Better string methods for TableColumnChange

---

plugins/destination/plugin_testing_migrate.go

Extracted from https://github.com/cloudquery/plugin-sdk/pull/694.
`readAll` does not guarantee resources are returned in order of insertion. In other tests we sort the resources read by sync time, then by CqId (though not sure how sorting by CqId helps as it's random).
Since in the migrate tests we use the same sync time for both insertions using the same method as other tests doesn't work.
Instead this PR uses `testify` contains method to check that the new resource exists in the resources read (we already check the count a bit before that
---

fix(test-migrate): Ignore order when comparing resources read

---

plugins/destination/plugin_testing_migrate.go

Extracted from https://github.com/cloudquery/plugin-sdk/pull/694.
Some destinations need at least one not null column (for example a sorting key in ClickHouse). This PRs adds the CqId column for tables created during migrate tests.
I think this is also closer to reality as we always have that column in our schema.
---

fix(test-migrate): Add CqId to migrate tests tables

---

plugins/destination/plugin.go

Follow up to https://github.com/cloudquery/plugin-sdk/pull/702.
Since we add CqID as the source plugins level:
https://github.com/cloudquery/plugin-sdk/blob/47440c2fc485c0609a481f5a6d6f12d00f530402/plugins/source/plugin.go#L78
https://github.com/cloudquery/plugin-sdk/pull/702 doesn't work unless sources are using the latest SDK.
This PR adds it as the destination level too, similar to `NotNull`
---

fix(destination): Set CqID to unique at the destination level

---

schema/array.go
schema/inet_test.go
schema/resource.go

fix: Cleanup code

---

plugins/source/scheduler_dfs.go

Related to https://github.com/cloudquery/plugin-sdk/issues/713. This PR detects duplicated client IDs, sends a sentry report when that happens and also logs a warning.
It not this does not skip those clients (yet). I'll do a follow up based on the sentry data as we can have duplicate clients due to:
1. User errors creating a configuration that generates duplicated clients like in https://github.com/cloudquery/cloudquery/pull/8099
2. Plugins bug, not implementing the ID method correctly
---

feat(multiplex): Detect duplicated clients

---

schema/json.go
schema/json_test.go

Fixes https://github.com/cloudquery/plugin-sdk/issues/622
See docs about the default behavior of `json.Marshal`:
https://pkg.go.dev/encoding/json#Marshal
See also https://pkg.go.dev/encoding/json#Encoder.SetEscapeHTML:
---

fix(types-json): Disable HTML escaping during JSON marshalling

---

schema/timestamptz.go

Fixes https://github.com/cloudquery/plugin-sdk/issues/700
Tested this on quite a few plugins. Most send `time.Time` in UTC already (`nil` location).
The only impact I've seen is on this AWS resource:
https://github.com/cloudquery/cloudquery/blob/380bcddff9406d12b7de343dd4dd002c95b46f0f/plugins/source/aws/resources/services/iam/credential_reports_fetch.go#L66
which for some reason results in a `time.Time` with a location with an empty name, so that would be converted to UTC.
Another impact is on the Stripe plugin that uses `int64`. Since `time.Unix` returns a `time.Time` with local timezone, now it will be converted to `UTC`.
---

fix(types-timestamp): Ensure timestamp is UTC

---

caser/caser.go
caser/caser_test.go
plugins/source/.snapshots/TestGeneratePluginDocs-JSON-__tables.json
plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-incremental_table.md
plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-relation_relation_table_a.md
plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-relation_relation_table_b.md
plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-relation_table.md
plugins/source/.snapshots/TestGeneratePluginDocs-Markdown-test_table.md
plugins/source/docs.go
plugins/source/options.go
plugins/source/plugin.go
plugins/source/templates/table.md.go.tpl
schema/table.go

This adds the ability to set titles for tables, and starts rendering them in the documentation. 
For example, docs for an example AWS table will now be rendered as:
```
This table shows data for AWS Access Analyzer Analyzer Findings.
```
This change should help human readers more quickly parse what a table is about, and in some cases developers may want to change the `Title` attribute to make it more descriptive. It is also useful for search, as many search engines will not tokenize on the underscores, leaving these pages excluded from relevant searches.

feat: Add ability to store table titles and render them in documentation

---

transformers/struct.go
transformers/struct_test.go

While using `transformers.WithPrimaryKeys` option there is an odd behavior being observed, where the unwrapped struct field also gets promoted to be PK.
Consider the following example:
```
type A struct {
ID string
B B
}
type B struct {
ID string
}
```
Currently, if `transformers.WithPrimaryKeys("ID")` option was used to transform struct `A` we would get the following columns:
* `id`: PK, taken from `A`
* `b_id`: PK, taken from `B`
However, with the current change, the following becomes possible:
| `transformers.WithPrimaryKeys` | `id` is PK | `b_id` is PK |
| --- | --- | --- |
| `"ID"` |  `true` | `false` |
| `"B.ID"` |  `false` | `true` |
| `"ID", "B.ID"` |  `true` | `true` |

fix(transform): Use path instead of field name for PK options

---

testdata/testdata.go

Made a small mistake in the GenTestData function :) 
(Note: this PR is to the `feat/arrow_update` branch)

feat: Null rows should go second

---

internal/memdb/memdb.go
plugins/destination/plugin_testing.go
plugins/destination/plugin_testing_migrate.go
plugins/destination/plugin_testing_overwrite.go
plugins/destination/plugin_testing_overwrite_delete_stale.go
plugins/destination/plugin_testing_write_append.go

fix: Destination testing memory leak

---

schema/arrow.go

This should solve bunch of issues that we have with NullValues and StripNulls logic propagated to all our destination plugins. Apparently [Valid](https://github.com/apache/arrow/pull/35161#discussion_r1170516104) utf8 string can't have null values in the middle of the string so we should just strip those in our type system (it can have at the end or the start but I suggest actually stripping those down as well as it's really unnecessary as far as I know and it exist prob for some archaic reason like sending a string over the wire without any additional encoding/protocol, which we have via arrow).
Once we move sources to arrow we will add the validation/strip on the source side.

fix: Disallow null character in strings per utf8 spec

---

plugins/destination/managed_writer.go

Our latest guideline is that plugins are responsible for releasing their resources.

fix: Undo release of all resources in managed writer

---

testdata/testdata.go

This will work for now but we will improve it later when we work more on our testing suite for destinations

fix: Truncate timestamp to millisecond in dest testing

---

internal/memdb/memdb.go
internal/memdb/memdb_test.go
plugins/destination/plugin_testing.go
plugins/destination/plugin_testing_migrate.go
plugins/destination/plugin_testing_overwrite.go
plugins/destination/plugin_testing_overwrite_delete_stale.go
plugins/destination/plugin_testing_write_append.go
testdata/testdata.go

Following this short discussion - https://github.com/apache/arrow/issues/35232
It seems we don't really need to use Retain/Release outside the arrow library. We can always bring this back in the future if we would like to experiment if this brings better memory performance then the default go allocator.

fix: Use Go memory allocator for arrow

---

plugins/destination/plugin_testing.go
plugins/destination/plugin_testing_migrate.go
plugins/destination/plugin_testing_overwrite.go
plugins/destination/plugin_testing_overwrite_delete_stale.go
plugins/destination/plugin_testing_write_append.go
testdata/testdata.go

This should fix some flakey tests for destination and also fix germlin - https://github.com/cloudquery/cloudquery/pull/10188

fix(testing): Add sorting for testing dest migrations

---

schema/table.go
transformers/struct.go
transformers/struct_test.go

Closes https://github.com/cloudquery/cloudquery/issues/10274
I went for the simple approach of not accepting the json tag value if it's going to result in an invalid column name.

fix: TransformWithStruct/DefaultNameTransformer change for invalid column names

---

plugins/destination/plugin_testing_migrate.go

We saw some bugs when the migration code wasn't reliable and, if we ran safe migration after forced one, there would be conflicts reported (where they shouldn't have been).
This extra test ensures that the destination is in sync what it scans from database and what is taken from spec.

feat(test): Add double migration test

---

clients/destination/v0/destination.go

Make sure time values are truncated uniformly across all operating systems and in line with the arrow casting

feat: Time values are truncated uniformly

---

.github/ISSUE_TEMPLATE/bug_report.yml

Same as https://github.com/cloudquery/cloudquery/pull/10276
---

chore(issue-templates): Remove needs-triage label from issue templates

---

.github/workflows/add_tags.yml
.github/workflows/lint_golang.yml
.github/workflows/lint_markdown.yml
.github/workflows/pr_title.yml
.github/workflows/release-pr.yml
.github/workflows/unittest-post.yml
.github/workflows/unittest.yml

The default GitHub Actions timeout is 6 hours. This PR sets all jobs timeouts to 10m to avoid things like:
https://github.com/cloudquery/plugin-sdk/actions/runs/4753306214/jobs/8444724190 (This Windows job timed out after 6 hours)
---

chore(ci): Add timeout to CI jobs

---

plugins/destination/plugin_testing_write_append.go

Discovered while performing testing for #818 in https://github.com/cloudquery/cloudquery/pull/10557

chore(test): Table for write append should also be modeled with timestamp

---

types/inet.go
types/inet_test.go
types/json.go
types/json_test.go
types/mac.go
types/mac_test.go
types/uuid.go
types/uuid_test.go

fix(arrow): Allow empty and `nil` valid param in `AppendValues`

---

schema/testdata.go
schema/testdata_test.go

There was a bug in the last implementation causing many types to be missing; it's always that final refactor you do 😄 
This time I added a sanity check for the testdata generation to make sure it can't be catastrophically broken without us knowing about it.

fix: Fix test column generation

---

internal/memdb/memdb.go
plugins/destination/plugin_testing_overwrite.go
plugins/destination/plugin_testing_overwrite_delete_stale.go
plugins/destination/plugin_testing_write_append.go

Reverts cloudquery/plugin-sdk#878
As far as I can see there is no need for this because over the wire it is always flattened anyway and in general I think we should move to always flatten structure as it causes more harm then good.

feat: Revert "feat(test): Test writing to a child table"

---

internal/servers/destination/v0/destinations.go
schema/table.go
schema/table_test.go

A bit more footgun in old protocol.

fix: Flatten V2 tables

---

internal/memdb/memdb_test.go
plugins/destination/plugin_testing.go
plugins/destination/plugin_testing_migrate.go
plugins/destination/plugin_testing_overwrite.go
plugins/destination/plugin_testing_overwrite_delete_stale.go
plugins/destination/plugin_testing_write_append.go
plugins/destination/strip_nulls.go
schema/testdata.go
schema/testdata_test.go
serve/destination_v1_test.go

- Skipping of null values in lists when doing comparisons is necessary for BigQuery tests to pass right now, because BigQuery does not support null values in repeated columns. To keep the migration to Arrow backwards-compatible, we are opting to strip nulls in that case (for now), but we still want our automated tests to pass.
- This also refactors the test options. Previously you had to call `destination.PluginTestSuiteRunner` with options from the `schema` package, which is a bit unusual and counter-intuitive, and makes it hard to extend with options that relate specifically to the test suite runner. This changes it so that the options passed in are from the `destination` package and passed through to the `schema` package. It's a breaking change, but this functionality hasn't been out …

feat: Refactor test options and allow skipping of nulls in lists

---

plugins/destination/plugin_testing.go
plugins/destination/plugin_testing_migrate.go
plugins/destination/plugin_testing_overwrite.go
plugins/destination/plugin_testing_overwrite_delete_stale.go
plugins/destination/plugin_testing_write_append.go
schema/testdata.go

Needed for mongodb https://github.com/cloudquery/cloudquery/pull/10819

feat: Add precision options for dest testing

---

transformers/struct.go
transformers/struct_test.go

Without this, attempting to transform an `[]any` column results in panic:
> panic: failed to transform table vercel_teams: failed to add column for field Profiles: failed to transform type for field Profiles: unsupported type: interface
Which is different from v2 behavior.

fix: Transform `[]any` as `JSON`

---

go.mod
go.sum
plugins/destination/plugin_testing.go
schema/testdata.go

This adds:
- support for testing decimal types
- support for testing maps (only string and int keys for now)
- randomization for values based on a given seed. Because a seed is used, the tests are still 100% reproducible, but it allows us to test values closer to the min/max of integer ranges and gives us different keys to test in maps
I found at least 4 surprising bugs in the Elasticsearch implementation through this. Destinations that don't want to support these features right now can still opt to skip the types.

fix: Test Decimal type, map type and larger number ranges

---

scalar/binary.go
scalar/binary_test.go
scalar/bool_test.go
scalar/float_test.go
scalar/uuid.go
scalar/uuid_test.go

Follow up to https://github.com/cloudquery/plugin-sdk/pull/922 to handle nil `*[]byte]` in `uuid` and `binary`.
Also added some tests to floats I can extract to another PR.
This is required for supporting `nil` values in https://github.com/cloudquery/cloudquery/pull/11115.
Discovered by generating test data with the [2 rows option](https://github.com/cloudquery/cloudquery/pull/11115#discussion_r1211284293) cc @candiduslynx.
---

fix(scalar): Handle nil pointer to []byte in uuid and binary

---

scalar/decimal.go
scalar/decimal_test.go

Follow up to https://github.com/cloudquery/plugin-sdk/pull/937, also needed for https://github.com/cloudquery/cloudquery/pull/11115
When reading data from a database it is common to pass a pointer to a value to support reading `nil` values, so the type of the value read is a pointer to a pointer.
Without this PR, if someone uses the decimal scalar they need to dereferences the pointer manually before setting the scalar value.
---

feat(scalar): Support pointer dereferencing in decimal

---

scalar/int.go

Removing this for now until we change int64 to uint64 in applicable sources. In any case this doesn't have any affect on destinations such as postgres

fix: Remove uint validation

---

docs/markdown.go

This should fix an error on windows where file couldn't be removed because it was still open

fix: Close files in docs

---

scheduler/scheduler.go
scheduler/scheduler_test.go
writers/batch.go
writers/mixed_batch.go

This add JSON marshaling / unmarshaling to the scheduler options, as well as some validation so that it can be used in source plugins that wish to use this option in their spec.
Other changes:
- lowering the default concurrency to 50000 in preparation for the v4 SDK release
- updating some names to be more consistent with Go naming conventions
- make default writer values public for use by plugins

fix: Update scheduler for JSON marshal / unmarshal

---

plugin/testing_write_migrate.go

fix: Enable double migration test

---

plugin/nulls.go
plugin/testing_write.go

fix: Put null helpers back

---

.github/workflows/unittest.yml

Trying large runner. CI is quite slow here which becomes a bit of a bottlenack on version upgrade when we have a lot of PRs. maybe caching is also a problem.

chore: Try larger runners

---

writers/streamingbatchwriter/streamingbatchwriter.go

So that workers aren't stopped when a single client's data ends. Calling `Close()` multiple times (or calling `Write` afterwards) would end up in a panic.

fix(writers): Require `Close()` for `StreamingBatchWriter`

---

writers/batchwriter/batchwriter.go
writers/streamingbatchwriter/streamingbatchwriter.go

I believe that the batch timeout should be a guarantee of a message being delayed by no longer than X amount of time. This means that we shouldn't reset the ticker every time a message is received, because then a message could be delayed for a very long time if a slow trickle of messages is coming in. This change fixes this issue and guarantees a message to be flushed within at most X duration.
For more context, see this PR and message https://github.com/cloudquery/plugin-sdk/pull/1055#discussion_r1251726213

fix: Fix timer logic in batch writers

---

plugin/testing_upsert.go
plugin/testing_write_delete.go
plugin/testing_write_insert.go
plugin/testing_write_migrate.go

This adds back assertions on the record data in destination writer tests. I'm not sure if we also need to handle ordering somehow here, but I think we can follow up with a fix for that if necessary.

fix: Check record data in tests

---

scalar/scalar.go
scalar/struct.go
scalar/struct_test.go
schema/testdata.go

Some fixes to the scalar and testing code:
- use `AppendTime` in `AppendToBuilder` to take different time units into account
- base64 decode binary-encoded JSON strings when the type calls for it in struct `Set()`, otherwise the binary data gets interpreted as a string and the results are incorrect
- exclude the JSON type from list tests, we didn't support that before and don't need to introduce it now

fix: Conversion and test fixes

---

writers/batchwriter/batchwriter.go
writers/mixedbatchwriter/mixedbatchwriter.go
writers/mixedbatchwriter/mixedbatchwriter_test.go
writers/streamingbatchwriter/mocktimer_test.go
writers/streamingbatchwriter/streamingbatchwriter.go
writers/streamingbatchwriter/streamingbatchwriter_test.go
writers/ticker.go

Follow-up for https://github.com/cloudquery/plugin-sdk/pull/1056

refactor(ticker): Don't reset manually

---

plugin/testing_write_migrate.go

We should check the first record higher up, because after the migration it will have an additional column and is therefore bound to differ from the original record.

fix: Fix test assertions for records

---

schema/testdata.go

`c.Type.ID()` is same for all Arrow extension types so instead of excluding the JSON type from list testdata, it excludes all extensions.

fix(testdata): Exclude only the correct type

---

transformers/tables.go

// Apply applies the given transformers to the given Tables, and recursively on the relations.
// This is useful for applying transformers that are not defined in the table definitions. To apply the table-definition transformers, use TransformTables.

feat(transformers): Add `Apply` to apply extra transformations

---

internal/memdb/memdb.go
plugin/testing_write_insert.go

Shuffling missed a case (I think) because we were using the same seed every time. Iterating over the items in reverse should have the same effect and is still deterministic.
Same fix as in https://github.com/cloudquery/plugin-sdk/pull/1074 but also adds a test for it.

fix: Reverse order of records in memdb

---

writers/batchwriter/batchwriter.go
writers/mixedbatchwriter/mixedbatchwriter.go
writers/mixedbatchwriter/mixedbatchwriter_test.go
writers/streamingbatchwriter/mocktimer_test.go
writers/streamingbatchwriter/streamingbatchwriter.go
writers/streamingbatchwriter/streamingbatchwriter_test.go
writers/ticker.go

This updates the ticker logic in the batch writers to reset the ticker when a flush happens. This is better, as it still guarantees that a message won't be delayed by more than batch_timeout, but we don't risk flushing a very small batch because we must flush at regular intervals either.
The choice of resetting _after_ the flush is deliberate: it means that the maximum amount of time between flushes is:
```
max_time = flush_time + batch_timeout
```
otherwise we could do:
```
max_time = batch_timeout
```
but if a flush were to then longer than the batch timeout, we can end up in a cycle of flushing again immediately after the previous flush finishes.

fix: Reset timers on flush

---

plugin/testing_upsert.go
plugin/testing_write_insert.go

Turns out TP isn't observed in InsertAll/UpsertAll. Needed for https://github.com/cloudquery/cloudquery/pull/12145

fix(testing): Comply with given TimePrecision

---

plugin/testing_write_migrate.go

A more flexible approach than https://github.com/cloudquery/plugin-sdk/pull/1100
In plugin's migration handling code, there's no easy way to decide if we should drop the table or not for some plugins. If force flag is set, the plugin is allowed to drop previous data.

fix(testing): Force migrations should allow table drops

---

plugin/diff.go

1. Less data generated
2. Allows to account for unordered map keys (foe CH, for example)

fix: Check record equality before generating diff

---

writers/streamingbatchwriter/mocktimer_test.go
writers/streamingbatchwriter/streamingbatchwriter.go
writers/streamingbatchwriter/streamingbatchwriter_test.go
writers/streamingbatchwriter/unimplemented.go

Fixes the hang [issue](https://github.com/cloudquery/cloudquery/issues/12793) with non-append mode when a dest is using `UnimplementedDeleteStale`.
- This also makes it so that it closes things when Write is done: Otherwise our testing framework confuses things (by invoking Write multiple times for multiple tests in the same plugin, I think).
We're noticing this now because of https://github.com/cloudquery/cloudquery/pull/12765, as other plugins using this writer (file based plugins) don't support migration operations.
Also makes it so that you don't need to call Close() on plugin deinit (but it could still be a good idea if Write was interrupted)

fix(writers): StreamingBatchWriter hangs with non-append mode

---

go.mod
go.sum
internal/servers/plugin/v3/plugin.go

Goes with https://github.com/cloudquery/plugin-pb/pull/17 and https://github.com/cloudquery/plugin-pb-go/pull/84
---

fix(plugin-tables): Add missing `skip_dependent_tables`

---

schema/table.go
schema/table_test.go

This adds an `UnflattenTables` method to the `Tables` type, the opposite operation of `FlattenTables`.
Until now, destination plugins were the only part of the code that needed to decode Arrow schemas to tables, and destinations don't need relational information. Now that docs generation is moving to the CLI, however, we need to be able to reconstruct the original relational structure in order to accurately reflect it in the docs.
Rather than modifying `FlattenTables`, which would not be backwards-compatible, I have opted to add a new method that the CLI can use. With this change in place, I am able to fully generate the docs for the AWS plugin from the CLI, with zero changes.

feat: Add Unflatten tables method

---

plugin/plugin.go
plugin/validate.go
schema/table.go
schema/table_test.go

Fixes https://github.com/cloudquery/plugin-sdk/issues/1106
Plugin validation was removed in https://github.com/cloudquery/plugin-sdk/pull/984/files#diff-95f04007d983a3bfdb080b338b9de5a8bbd73a3d65910fbe664f97788a9021b3.
As a result we don't validate tables and columns anymore, see resulted bug in https://github.com/cloudquery/cloudquery/pull/12428.
This PR brings it back and per a better option puts the validation in the `Init` method. Other options:
1. Have each plugin call `.validate` on the plugin side, probably after transformation [here](https://github.com/cloudquery/cloudquery/blob/03fae6d803a4e2ac00ff83d9e90a4169b247c346/plugins/source/aws/resources/plugin/tables.go#L565). Downside that each plugin needs to implement the call
2. Have the validation done as a part of …

fix: Bring back plugin validation

---

plugin/diff.go
plugin/nulls_test.go
plugin/testing_upsert.go
plugin/testing_write_delete.go
plugin/testing_write_insert.go
plugin/testing_write_migrate.go
schema/testdata.go

Part of https://github.com/cloudquery/cloudquery/issues/13153
This changes the semantics of `testdata.Generate` from `generate opts.MaxRows` records to `generate a single record with opts.MaxRows rows`

fix: Change `testdata.Generate` signature

---

internal/servers/destination/v1/destinations.go

Migrate messages are already sent in the CLI here https://github.com/cloudquery/cloudquery/blob/eab200d6944c54db5ef6d9a81b290ed6b8ddd06f/cli/cmd/sync_v2.go#L145 (during sync) and here https://github.com/cloudquery/cloudquery/blob/eab200d6944c54db5ef6d9a81b290ed6b8ddd06f/cli/cmd/migrate_v2.go#L66 (during migrate).
Without this fix, if you have a v2 source and a v3 destination `sync` will run migration twice, and `sync --no-migrate` will run migration once
---

fix: Don't send migrate messages in destination v1 write

---

serve/package.go
serve/package_test.go

We should have a version in the package.json file so that we can check compatibility with the CLI.

fix: Add schema version to package.json

---

scheduler/scheduler.go
scheduler/scheduler_shuffle.go

Falling somewhere between DFS and Round Robin, the `shuffle` scheduler uses randomization with a fixed seed to spread the load across tables and clients more evenly.

feat: Add shuffle scheduler

---

plugin/plugin.go

Documentation generation will fail otherwise.
Follow-up for #1214

fix: Validate spec only when connection is established

---

internal/memdb/memdb.go
serve/package.go
serve/package_test.go
serve/plugin_test.go

We might want to refactor this to no (ab)use the MemDB plugin but I think this is ok for now. Also we should call `FlattenTables` otherwise we only output the top level ones
---

fix(package): Normalize tables when writing tables.json

---

examples/simple_plugin/plugin/client.go
plugin/plugin_package.go
serve/package.go
serve/package_test.go

This adds a new `type` (`source` or `destination`) argument to the `package` command, and switches the ordering of arguments bit (since we're making a breaking change to it anyway). The `type` is written to package.json as well, and if it is `destination`, we don't create a `tables.json`.

fix: Skip tables.json when packaging destinations

---

plugin/plugin_package.go
serve/package.go
serve/package_test.go

I realized existing plugin configs use the word `kind` (e.g. `kind: source`) and not `type`. Let's just stick to one word everywhere for consistency.

fix: Rename plugin type -> kind for consistency with existing configs

---

scheduler/scheduler.go
scheduler/scheduler_test.go
schema/table.go

feat: Provide User with actionable error message when no tables are configured for syncing

---

serve/package.go

Fixes https://github.com/cloudquery/plugin-sdk/issues/1248
Another option that we could do (or do both) is handle `NoConnection` in all destinations.
---

fix(package): Don't init destinations during package

---

plugin/options.go
plugin/plugin.go
serve/package.go

This adds support for conditionally linking C libs when building plugin executables. CGO_ENABLED plugins (sqlite and duckdb) fail to run on Alpine Linux distributions because of missing C libraries needed to execute the code. See https://github.com/cloudquery/cloudquery/issues/14465.
The fix is to include those missing libraries into the executable that is created by `go build`:
`CGO_ENABLED=1 go build -ldflags="-linkmode external -extldflags=-static"`

feat: Add support for conditional static linking of C lib to builds

---

plugin/testing_write.go

fix: Enable Skipping of DeleteRecord tests

---

serve/package.go

This applies the new static linking feature only for Linux platforms

fix: Make static linking conditional only for Linux

---

go.mod
go.sum
premium/usage.go
premium/usage_test.go

This will allows a client to update the usage asynchronously. The updater will only call the API when a configurable number of rows have been updated or a timeout is reached. In addition the updater will flush any remaining rows before closing.
If an error is encountered then an exponential backoff up to a max number of retries or a maximum wait time (relative to the start time of the last query) will be followed.
In addition, if the server replies with a status of `429` and includes a `Retry-After` header, then the client will wait that number of seconds before retrying.
It might be worth considering just using a retry library also e.g. https://github.com/avast/retry-go.

feat: Adding a batch updater to allow usage updates to be batched

---

premium/usage.go

If remaining rows is not set, it indicates an infinite number of remaining rows (ie. the plugin is free)

fix: Fix nil pointer dereference when remaining rows not set

---

premium/usage.go

Right now the error users get when the team is not set is `failed to configure quota monitor: failed to get usage: 404 Not Found`. The recent CLI change in https://github.com/cloudquery/cloudquery/pull/15119 will ensure that the team should mostly get set, but there can still be cases where users are in multiple teams and forget to run `cloudquery switch`. In such a case, a friendlier error would be helpful.

fix: Return clearer error when team name empty or not set

---

examples/simple_plugin/go.sum
premium/usage.go

Retreive the team associated with an API key to allow usage tracking against a team name
fixes: https://github.com/cloudquery/cloudquery-issues/issues/893

fix: Retrieve team for api key

---

premium/usage.go
premium/usage_test.go

Related to https://github.com/cloudquery/cloudquery-issues/issues/990 (internal issue). Currently if the user is not logged in and you try to initialize the usage client it fails with an error the team is not set and tells the user to run `cloudquery switch` (since `getTeamNameByTokenType` fails).
This PR adds logic to try and get the token during initialization to show a more relevant error message with a hint for the user  to run `cloudquery login`
---

fix: Fail early on usage client init if token is not set

---

scheduler/scheduler.go
scheduler/scheduler_dfs.go

This pr introduces a rate semaphore that limits the number of simultaneous go routines that can be resolving the same table + client to just 10. Prior to this a single table could be using all of the available concurrency to resolve a single table. This alleviates the problem where nested tables get throttled because the load is not spread across all client/table pairs but is concentrated on a single client and table.
I will update this PR with a benchmark case once #1410 gets merged

feat: Individual Table and Client rate limit

---

premium/monitor.go
premium/monitor_test.go
premium/tables.go
premium/usage.go

Updates the usage limit message to also account for the case where the free quota limit is reached, and give users a clear action to perform.

fix: Update usage limit message

---

schema/validators.go
schema/validators_test.go

I'm not sure if there's a better way, but this seems to work for me.
~Still testing cases.~
Fixes https://github.com/cloudquery/cloudquery/issues/15707

fix(tests): Find empty columns for JSON types

---

faker/faker.go
faker/faker_test.go

This helps simplify codegen/mockgen scenarios, where some enums aren't faked correctly. This way the template struct can have correct enums in a specific field, while faking other fields. Used in stripe plugin.

feat: Faker should preserve previous values, if set

---

serve/plugin.go

This is a minor improvement to expose otel headers and url_path as flags. I tested it with OpenObserve - https://openobserve.ai/docs/ingestion/traces/go/#clone 
Example running a plugin with OpenObserve running locally
```
go run main.go serve --otel-endpoint localhost:5080 --otel-endpoint-headers "Authorization: Basic TOKEN" --otel-endpoint-insecure --otel-endpoint-urlpath "/api/default/v1/traces"
```

feat: Expose otel headers and url_path as flags

---

plugin/plugin.go
premium/offline.go
premium/offline_test.go
serve/plugin.go

feat: Support multiple and/or specific plugin licenses

---

scalar/interval.go

Extracted from https://github.com/cloudquery/plugin-sdk/pull/1476

fix: Eternal recursion in `scalar.MonthInterval`

---

scalar/inet.go
scalar/inet_test.go
scalar/interval.go
scalar/mac.go

Instead of https://github.com/cloudquery/plugin-sdk/pull/1476
Closes https://github.com/cloudquery/plugin-sdk/issues/1475
The `typed nil` also can be observed in https://github.com/cloudquery/cloudquery/pull/16221

fix: Verify `nil` value consistently

---

plugin/testing_write.go
plugin/testing_write_migrate.go
schema/testdata.go

Destinations can now verify the new `MoveToCQIDPrimaryKey` change type that was introduced in #1470 
Depends on #1479

feat: Expose Migration test for new special case for moving to `_cq_id` as only primary key

---

scheduler/scheduler.go
scheduler/scheduler_test.go
schema/table.go

Fixed a case where no sync message would be sent

fix: When `_cq_id` SyncMigrateMessage not sent

---

plugin/options.go
plugin/plugin.go
plugin/plugin_package.go
serve/package.go

Instead of passing `static` option we should allow for env var values overrides in the package call.

fix: Better build overrides

---

plugin/testing_write.go
plugin/testing_write_delete.go

Saving `*testing.T` inside the `Suite` to use it later in sub-tests results in this error if we have a failed test:
> testing.go:1490: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
We shouldn't get this error.
Other parts of the test suite return `error` (signature is `func (s *WriterTestSuite) testName(context.Context) error`) and we do a simple `t.Fatal` in the main test body, but for DeleteStale tests we use `testify/require` inside the test so we need to access `*testing.T`.

fix: Remove access to parent tests in test suite

---

plugin/plugin.go

Rather than using `-src` for all plugins this PR uses the `plugin.Kind()` to set `-source` or `-destination`

fix: Default Plugin logger assumes plugin is a `source`

---

scalar/list.go
scalar/list_test.go
scheduler/scheduler.go

Without this, lists from the test source (at least, could be more plugins/cases) get persisted as `[]`
I'm still not 100% sure how the lists end up getting encoded to JSON, probably we use Arrow's `.ValueStr` and/or `.GetOneForMarshal` somewhere.
Called from table resolver - source plugins need this fix.

fix: Support list scalars from JSON

---

plugin/testing_write.go
plugin/testing_write_delete.go
plugin/testing_write_insert.go
plugin/testing_write_migrate.go
plugin/testing_write_upsert.go
schema/testdata.go

For OpenSearch (and presumably ElasticSearch) arrays (even in JSON objects) are limited to the same data types. This adds a configuration option to the writer test suite to only use the same data type in the JSON example data - allowing the test suite to be used for the OpenSearch plugin. Currently JSON objects in the ElasticSearch and OpenSearch plugins are mapped to strings.

feat: Allow homogeneous data types to be configured

---

plugin/plugin.go
plugin/validate.go

Not all source plugins are able to generate the list of tables at initialization time. For example S3 source needs to list and then download the object in order to generate the table. This can have a super high cost as a bucket can have near limitless amount of data

feat: Skip table validation during init

---

plugin/testing_write.go
plugin/testing_write_migrate.go

Some destinations don't support all migrations types. This allows them to opt out

feat: Enable destinations to completely skip migration that are not supported

---

premium/usage.go
premium/usage_test.go

Every time we add a new token type (e.g. test connection token type) the existing plugin versions that use the usage client can't use the new token type since the default on unknown token type is to fail when trying to get the team name.
This PR updates the code to fallback to `_CQ_TEAM_NAME` so even if a new token type is added we try to get the team name from `_CQ_TEAM_NAME`.
This will ensure that if we add a new token type, existing versions can still get the team name as long as `_CQ_TEAM_NAME` exists.
---

feat: Handle unknown token types when getting team name in usage client

---

Makefile

Remove noisy BatchWriter benchmarks
Still keeps it in `make benchmark`

chore: Remove writer benchmarks from CI

---

premium/monitor.go

The link is missing the `cloud.` subdomain

fix: Fix link to billing page

---

examples/simple_plugin/go.mod
examples/simple_plugin/go.sum
go.mod
go.sum
premium/usage.go
premium/usage_test.go

Implements changes requested in [#1502](https://github.com/cloudquery/cloudquery-issues/issues/1502).
The solution consists of adding a new func `IncreaseWithTableBreakdown(table string, rows uint32)` to the existing client, which we can declaratively replace in required non-database plugins incrementally.

feat: Allow reporting usage as breakdown by table

---

premium/usage.go
premium/usage_test.go

The increase team usage endpoint now returns the desired batch limit and min/max update interval based on the team plan. The plugin sdk should now set the batch updater configuration to the values indicated by the API.
Refs: https://github.com/cloudquery/cloudquery-issues/issues/1551

feat: Re-configure batch updater using response headers

---

internal/servers/plugin/v3/plugin.go

`failed to sync records: %w` is already used, by `Server.Sync()`

fix: Correct error message on Read failure

---

plugin/plugin.go

Similar to https://github.com/cloudquery/cloudquery/pull/17994.
It keeps the code that checks that the schema itself is a valid to ensure plugins embed a valid one
---

fix: Remove JSON schema validation warnings

---

state/client.go

Currently source plugins using the `ConnectedClient` cannot be used with `append` only destinations as the `ClientOption` cannot be set. This PR exposes that option. This won't have any impact on CQ plugins as none of our plugins use `NewConnectedClientWithOptions`

feat: Enable `NewConnectedClientWithOptions` to set `ClientOptions`

---

internal/clients/state/v3/state.go
state/client.go

Return early, don't "export" (it's already under `internal/`) `table()`

chore: Code style in state

---

examples/simple_plugin/go.mod
examples/simple_plugin/go.sum
go.mod
go.sum
internal/servers/plugin/v3/plugin.go
scheduler/scheduler.go
scheduler/scheduler_dfs.go
serve/plugin.go

Closes [#1809](https://github.com/cloudquery/cloudquery-issues/issues/1809).

feat: Remove plugin option for logging error events to Sentry

---

schema/table.go
schema/table_test.go

Fixes https://github.com/cloudquery/cloudquery/issues/18206

fix: Don't include other relation siblings if not specified in config

---

serve/plugin.go

If you try to disable telemetry with plugins using the latest SDK you get this warning:
```
Flag --no-sentry has been deprecated, no-sentry option is deprecated and unused
```
The reason is that the CLI still sends this flag (ends up here https://github.com/cloudquery/plugin-pb-go/blob/aeb0d17fd2577caacbfdadfecc89fa4a1357cca6/managedplugin/plugin.go#L448), so new plugins print a warning.
We can't remove the sending of the flag, since then older plugins will start sending sentry errors 🙃 
I suggest we remove the log warning for now, and give users a bit of time to upgrade plugins, then remove the flag altogether

fix: Remove no sentry deprecation warning

---

scalar/errors.go
scalar/json.go
scalar/json_test.go

Reverts cloudquery/plugin-sdk#1743

fix: Revert "fix: Allow marshaling plain string values into JSON scalars"

---

scheduler/metrics.go
scheduler/scheduler.go
scheduler/scheduler_dfs.go

Follow up to https://github.com/cloudquery/plugin-sdk/pull/1757, as it seems we're accessing table metrics in other Go routines (e.g. `resolveResource`)
---

fix: Use Atomic Pointer for updating duration metric

---

serve/opentelemetry.go

Fixes https://github.com/cloudquery/cloudquery-issues/issues/1980 (mostly)
---

fix: Log OTEL errors as warning level instead of debug

---

schema/arrow.go
schema/column.go
serve/package.go
transformers/options.go
transformers/struct.go
transformers/struct_test.go

Part of https://github.com/cloudquery/cloudquery/issues/2023 ~~Still WIP and depends on https://github.com/cloudquery/cloudquery-api-go/pull/196~~
---

feat: Add JSON type schema

---

transformers/struct.go
transformers/struct_test.go

Otherwise we generate too big gRPC messages and the tables command fails:
https://github.com/cloudquery/cloudquery-private/actions/runs/10076465888/job/27856903583#step:6:15
---

fix: Reduce JSON column schema nesting

---

go.mod
helpers/retryablehttp/logger.go

This allows plugins that use https://github.com/hashicorp/go-retryablehttp to easily log retries as plugins use `github.com/rs/zerolog`
---

feat: Add `zerolog.Logger` to `retryablehttp.LeveledLogger` adapter struct

---

helpers/remoteoauth/tokenautheditor.go
helpers/remoteoauth/tokenauthtransport.go

These helpers can be used to inject dynamic tokens into requests.
`TokenAuthTransport` is a `http.RoundTripper`, with optional custom rewriting capability
`TokenAuthEditor(oauth2.TokenSource)` returns a `func(context.Context, *http.Request) error` to be used as a `RequestEditorFn` in openapi clients.

feat: Add remoteoauth helpers (`TokenAuthTransport` and `TokenAuthEditor`)

---

scheduler/scheduler_round_robin.go
scheduler/scheduler_shuffle.go

`multiplex returned duplicate client` warning for incorrect multiplexers occurs only when `dfs` scheduler is used. This PR adds the same warning for `round-robin` and `shuffle` schedulers.
More context here: https://discord.com/channels/872925471417962546/1271466277189324831
---

feat: Add warning on duplicate clients for `round-robin` and `shuffle` schedulers

---

schema/table.go

`previous` is never set so shouldn't be stringified

fix: Fix panic when converting schema changes to string

---

helpers/remoteoauth/token_test.go
helpers/remoteoauth/tokenoptions.go

instead of `WithAccessToken`, which needed explicit default values and didn't support refresh tokens in non-cloud mode.

feat(remoteoauth): Add `WithToken` option

---

internal/clients/state/v3/state.go
serve/state_test.go
state/client.go

Fixes https://github.com/cloudquery/cloudquery-issues/issues/2435
---

feat: Make state client versioning the default, remove option

---

plugin/plugin.go
serve/plugin.go

Fixes https://github.com/cloudquery/cloudquery-issues/issues/2627
The wrong value in the `module` field is because of the bug fixed in https://github.com/cloudquery/plugin-pb-go/pull/421
---

fix: Ensure module field exists in all log messages

---

premium/usage.go
premium/usage_test.go

The problem is that there is no way to know if all rows have already been processed by the time `*BatchUpdater.Close()` is called. If they have been, then `numberOfUpdates()` will return 1 less than expected, causing the flakiness.
There are two ways to fix this:
- Make sure enough time passes between calls to `Increase()` and `Close()`. A call to `runtime.Gosched()` in the test before calling close could also help, but there are no guarantees. Timing-based tests are also generally icky.
- Keep track of whether `Close()` actually resulted in any processed rows, and adjust the expected number of updates if so. This has to advantage of working 100% reliably, eliminating the flakiness, at the cost of introducing a field only used for tests.
This commit implements the second approach.
This …

fix: Flaky usage tests

---

premium/usage.go

Non-empty headers always get parsed and if it's a valid Int/Uint it gets persisted. Including zero values.

chore: BatchUpdater: Protect against unrealistic values

---

premium/monitor.go
premium/monitor_test.go
premium/usage.go
premium/usage_test.go

The query interval is something we're introducing in the backend.

feat: Support for quota query interval header

---

premium/usage.go
premium/usage_test.go

I may have used the term "clean up" loosely.

fix: Clean up usage retry logic

---

premium/usage.go
premium/usage_test.go

fix: Correctly handle success in DryRun invocation

---

configtype/time.go

Fixes https://github.com/cloudquery/plugin-sdk/security/code-scanning/3
Fixes https://github.com/cloudquery/plugin-sdk/security/code-scanning/2
Fixes https://github.com/cloudquery/plugin-sdk/security/code-scanning/1
Technically a false positive since on 64 machines (we only compile to 64 bit) `int` and `int64` (`number` is `int64`) usually have the same size so no overflow
---

fix: Handle integer overflow

---

schema/resource.go
schema/resource_test.go

Fixes https://github.com/cloudquery/cloudquery-issues/issues/3004
---

fix: Validate missing PK components

---

examples/simple_plugin/plugin/client.go
scheduler/queue/worker.go
scheduler/scheduler_dfs.go
schema/meta.go
schema/resource.go
schema/table.go

We need to be able to store `_cq_client_id` on every table for certain use cases where we need to know where a row came from in terms of multiplexed clients.
This PR adds the ability for the SDK and all its schedulers to store `_cq_client_id` on all tables.
I added this feature to the example plugin in the SDK and it does store it properly:
If you want to try this yourself, please note that, very unfortunately, the simple plugin also stores a `client_id` column that is unrelated (and doesn't work, since it thinks it's supposed to be an integer).

feat: Enable storing _cq_client_id.

---

configtype/time.go
configtype/time_test.go
go.mod
go.sum

First option was using exported fields, but even that would require additional logic- e.g. what should happen, if the user provided input is `50 minutes ago` and the sync is run twice at different times?
I think this approach makes more sense, but let me know if there are any other ideas or comments to consider.
---
closes https://github.com/cloudquery/cloudquery-private/issues/6478

feat: Add way to get Configtype time value for hashing

---

.golangci.yml
docs/markdown.go
helpers/remoteoauth/token_test.go
schema/testdata.go

Fixes https://github.com/cloudquery/plugin-sdk/actions/runs/13367954470/job/37329892347?pr=2080
---

chore: Remove `errcheck` deprecated configuration

---

configtype/time.go

When generating table docs with table options, the new description will be used

feat: Add description to time JSONschema

---

transformers/nullable_field.go
transformers/options.go
transformers/struct.go
transformers/struct_test.go

Fixes https://github.com/cloudquery/cloudquery/issues/20286
Add `transformers.WithNullableFieldTransformer(func ...)` to allow the SDK user to have custom rules to decide for a field nullability.
This is especially useful when the user defines its struct with some pointers and some regular value types: we can have the that set `nil` for pointers, non `nil` for non-pointers.
---

feat: Add WithNullableFieldTransformer to transformers.TransformWithStruct options

---

internal/servers/plugin/v3/plugin.go

fixes https://github.com/cloudquery/cloudquery-issues/issues/3451
The CLI closes the context that the Transformer plugin uses upon completion of the sync. This is not an error, so the SDK should not raise it in the `Transform` function.
This error is benign in that the sync still works as expected, but it looks bad in the logs, which end up showing up in `cloudquery.log`, and it bubbles up to other products like Asset Inventory which happens to show errors in bright red colours.
Here's a typical current run
Here's a fixed run

fix: Ignore context cancelled errors.

---

faker/faker.go

Reverts https://github.com/cloudquery/plugin-sdk/pull/2087/files#diff-d23bd4e64abe4e710bc1f39711bda2ddc0d4a9a5c1ee80e7551787a0f81e2d5aL20 as it broke some plugins tests.
Underlying issue is that we call `getFakedValue` on the array of fields in https://github.com/cloudquery/plugin-sdk/blob/1298b36185f8d19e0a0c65f6f3958106565271c9/faker/faker.go#L65 so when operating on the pointer we share the max depth with the fields.
Reverting for now so it doesn't block the SDK update
---

fix: Revert faker pointer change

---

transformers/tables.go
transformers/tables_test.go

I spent too much time debugging a bug I had when I (meaning Cursor AI) auto complete `PrimaryKeyComponent: true` instead of `PrimaryKey: true` for me. Which means I had both PKs and PK components on the same table, causing `_cq_id` to only be calculated from the PK component, losing data when `pk_mode: cq-id-only` was enabled.
See https://github.com/cloudquery/cloudquery-private/pull/6902/commits/ef8762eb1f1a6624913e5ee9ff7a88e9e0944537
This PR adds a validation to ensure only either ones are defined, or not defined at all. This has to happen after the `TransformTables` call since columns can be configured manually as well
---

fix: Error if both PKs and PK components are set

---

schema/table.go
transformers/tables.go

This should allow us to control when we want to fix the issue seen in the PR here https://github.com/cloudquery/cloudquery-private/pull/7015
---

feat: Allow skipping PK components mismatch validation

---

docs/table_options.go
docs/table_options_test.go
docs/testdata/schema.json
docs/testdata/tableoptions.go
examples/simple_plugin/go.mod
examples/simple_plugin/go.sum
go.mod
go.sum

Adds code we commonly reuse in plugins to add the table options to the table description

feat: Add transformer to update table description with its table options

---

examples/simple_plugin/go.mod
examples/simple_plugin/go.sum
go.mod
go.sum
serve/constants.go
serve/plugin.go

Following up on the transformer hanging issue reported by a customer and addressed in PR [#2130](https://github.com/cloudquery/plugin-sdk/pull/2130):
Currently, the transformer plugin can increase the message size beyond the limit enforced in the sync method of plugin-sdk [1](https://github.com/cloudquery/plugin-sdk/blob/bc50fd3d2be414edba8f8ad5bb7739a012840bf1/internal/servers/plugin/v3/plugin.go#L267).
To accommodate scenarios where transformers or destination plugins need to handle larger messages than the source plugin, we should consider increasing this limit to provide more flexibility.
---

chore: Double the limit of grpc messages

---

premium/usage.go

Follow-up to https://github.com/cloudquery/plugin-sdk/pull/2106
Plugins use regular team API keys for usage reports, not platform-specific local API keys.

fix: Pass installation ID from env for usage report

---

writers/batchwriter/batchwriter.go

The current logic for `BatchWriter` does not flush `DeleteRecord` messages when the writer is flushed. This PR adds that flushing.
I'm also wondering whether we should add a call to `flushDeleteRecordTables` in https://github.com/cloudquery/plugin-sdk/blob/main/writers/batchwriter/batchwriter.go#L307-L315. WDYT?

fix: Flush DeleteRecord messages when batch writer is flushed

---

writers/batchwriter/batchwriter.go

The current logic for batch writing prevents us from cleanly testing the `DeleteRecord` handling in the plugin. Currently we have to set `BatchSize: 1` and send two `DeleteRecord` messages in the test, which is not the cleanest logic. This PR changes the logic so the batch is flushed when the batch size is reached, not exceeded (so for `BatchSize: 1` it will flush after one `DeleteRecord` is received).
This also matches the logic we have in https://github.com/cloudquery/plugin-sdk/blob/main/internal/batch/cap.go#L7.

fix: Change logic for batch writing to write when batch size is reached, not exceeded

---

state/client.go

We were able to validate grpc.NewClient works as expected after the upstream fix so there's nothing blocking us from upgrading it.

feat: Switch state grpc client to NewClient rather than DialContext

---

examples/simple_plugin/go.mod
examples/simple_plugin/go.sum
go.mod
go.sum
internal/servers/plugin/v3/plugin.go
message/sync_message.go
scheduler/queue/scheduler.go
scheduler/queue/scheduler_test.go
scheduler/queue/worker.go
scheduler/scheduler.go
scheduler/scheduler_dfs.go
scheduler/scheduler_shuffle_queue.go

This PR requires changes to plugin-pb 
---

feat: Add handling of error messages to sdk

---

premium/monitor.go

Make the error not tied to a month interval
---

fix: Improve usage error wording

---

plugin/diff.go

Cleans up https://github.com/cloudquery/plugin-sdk/pull/2226, https://github.com/cloudquery/plugin-sdk/pull/2220 and https://github.com/cloudquery/plugin-sdk/pull/2217.
I believe I found the issue and the fix is https://github.com/cloudquery/cloudquery/pull/21058
---

chore: Clean up diff functions

---

schema/table.go

In the ClickHouse destination, we want to add some additional information about table-level changes (sort keys, partition keys) to that provided by `GetChangesSummary`. However right now, that would mean duplicating quite a lot of code, so I would like to suggest that we instead make `GetColumnChangeSummary` public for use in this case and others like it.

feat: Make getColumnChangeSummary public for use in plugins
