cloudquery/plugin-sdk

.github/workflows/lint_golang.yml, .github/workflows/unittest.yml, CODEOWNERS, clients/template.go, go.mod, go.sum, schema/md_docs.go, schema/meta.go, schema/resource.go, schema/table.go, serve/serve.go, specs/source.go, specs/spec_reader_test.go
This should fix unit tests and mosts of the linting issues apart from one place which wasnt sure what is the issue there. 
---
=> fix: Tests and spec unmarshalling

.github/workflows/release-pr.yml
Not released yet https://github.com/google-github-actions/release-please-action/pull/555
=> chore: Remove changelog-notes-type

codegen/golang.go, codegen/golang_test.go
Add support for timestamp columns to v2 branch (previously they were converted to JSON)
=> feat: Support timestamp columns

codegen/templates/table.go.tpl
Add description field to tables
=> feat: Add table descriptions

.github/workflows/unittest.yml
Adds code coverage reports
---
=> chore: Add Codecov

plugins/source.go, schema/column.go, schema/meta.go
This will simplify implementation of destinations. Moreover this feature is not used in any of our plugins (maybe will never be) so no need to support it atm.
---
=> feat: Remove Unique constraint (support pks only)

codegen/golang.go, codegen/table.go, codegen/templates/table.go.tpl, schema/resource.go, schema/table.go
An example of usage here : https://github.com/cloudquery/cloudquery/pull/1706
---
=> feat: Add PreResourceResolver to accommodate list/detail pattern

plugins/source.go, plugins/source_test.go, schema/table.go, serve/serve_test.go
logger wasn't passed to source executor.
---
=> fix!: Logger wasnt passed to source plugin resulting no errors

codegen/golang.go, faker/faker.go, faker/faker_test.go, plugins/source.go, plugins/source_testing.go
https://github.com/bxcodec/faker had a lot of issues
including inherent race conditions and features we didn't need.
This introduces custom faker which will make our life easier
in mock tests.
---
=> feat: Add custom faker

plugins/source.go, schema/table.go, serve/serve.go
We will be logging everything as log and moving log analysis to external tools such as jq.
Also, for sentry we will be only looking for panics and not for incorrect classification as we dont classify anything anymore
Also discussed with @erezrokah and @hermanschaaf 
---
=> feat: Remove IgnoreError and send sentry only on panics

schema/table.go
This makes sure we always use `table` and not `table` and `table_name`  (maybe we can improve it in the future with zerolog `With` so we dont need to add it to ever log line)
---
=> feat: Make logs consistent

.github/workflows/lint_golang.yml, .github/workflows/unittest.yml, codegen/doc.go, docs/source_test.go, go.mod, schema/table.go, specs/spec_reader.go
https://tip.golang.org/doc/go1.19
=> chore: Upgrade to Go 1.19

codegen/golang.go, codegen/table.go
Per https://github.com/cloudquery/plugin-sdk/pull/75#pullrequestreview-1103324025.
We can just `skipFields` and `extraColumns` instead
---
=> feat!: Depracate override columns

codegen/templates/table.go.tpl
Similar to PreResourceResolver, this adds support for PostResourceResolver to the table template.
=> feat: Add PostResourceResolver to template

.golangci.yml, schema/resoruce_test.go
`unused-parameter` is reported on the deleted file
---
=> fix: Remove empty test and enable some lint rules

.golangci.yml, faker/faker.go, plugins/source.go, schema/filters.go, schema/meta.go, schema/resolvers.go, schema/resource.go, specs/spec.go
We have a bunch of useful lint rules disable since it would have taken a lot of work to fix all the issues.
With the new SDK we can start fixing the issues gradually
---
=> fix!: Enable var names lint rule and fix issues

plugins/source_testing.go
I was expecting my Azure mock tests that have relations to fail as I don't handle mocking the related APIs.
I was surprised to see them pass 🙃 
The reason is that we need to validate that we got the related resources too.
---
=> fix(testing): Validate all tables and relations

codegen/golang.go, codegen/golang_test.go, codegen/table.go
=> feat: Add minor improvements to WithUnwrap codegen options

specs/spec_reader.go
Required for https://github.com/cloudquery/cloudquery/pull/1847
---
=> feat: Add GetDestinations function to list all destinations

codegen/golang.go, codegen/golang_test.go, codegen/table.go
=> feat: Use JSON tag for column name if applicable

plugins/source_testing.go
I found quite a few issue where we use resource.Set but we dont define the column and the destination pluginfails to write because the column doesn't exist
---
=> feat: Validate undefined column in TestResource

codegen/golang.go, codegen/golang_test.go
Make default transformer exported to be able to use it in custom transformers that extend its functionality
---
=> feat: Make default transformer exported to use in custom transformers

codegen/golang.go, codegen/golang_test.go, codegen/table.go
This is take two of https://github.com/cloudquery/plugin-sdk/pull/139
Trying to get right the `WithTypeTransformer` so we wont have to change it in the near future as it's heavilly used external API.
I've also added error handling to all functions as we were basically ignoring all of them and printing to the screen is not the right approach catching those locally and in CI.
---
=> feat(codegen): Add WithTypeTransformer

codegen/column.go, codegen/options.go, codegen/table.go, codegen/table_test.go, codegen/transformers.go
Add `WithResolverTransformer` option (based on #150)
=> feat(codegen): Add `WithResolverTransformer` option

.golangci.yml
=> chore: Remove GCI from lint

specs/destination_test.go
=> test: Add test for spec validation

schema/meta.go, schema/resolvers.go
Doesn't seem like we should expose this resolver as a public API
---
=> feat!: Make CQUUIDResolver private

schema/resolvers.go
Related to https://github.com/cloudquery/plugin-sdk/issues/199
---
=> feat!: Rename ParentResourceFieldResolver to ParentColumnResolver

schema/resolvers.go
Fixes https://github.com/cloudquery/plugin-sdk/issues/197
---
=> feat!: Remove ParentIDResolver

CODEOWNERS
Set `CHANGELOG.md` to not have code owners so everyone with write access can merge release PRs
---
=> chore(codeowners): Set empty code owners for CHANGELOG.md

codegen/table_test.go, codegen/transformers.go, schema/column.go, schema/column_test.go
Add duration column type for #178 
---
=> feat(schema): Add schema.TypeTimeInterval

.github/.kodiak.toml
Automerge should be handled by renovate via https://github.com/cloudquery/.github/pull/350
---
=> chore: Remove Kodiak automerge in favor of Renovate

CODEOWNERS
This should allow auto merging of dependencies PRs as now those are blocked by code owner review
---
=> chore: Exclude more files from CODEOWNERS

plugins/source_docs.go
Extracted from https://github.com/cloudquery/plugin-sdk/pull/220
---
=> fix: Remove redundant error print

.github/styles/Vocab/Base/accept.txt, .github/workflows/lint_markdown.yml, CONTRIBUTING.md
Fixes some issues with our docs
=> chore(docs): Fix typos, broken links in markdown

clients/download.go
=> fix: Improve download message

clients/logging.go
I think copilot did bad job :)
=> fix: Logging level

clients/download.go
=> fix: Make progressbar work on small screens

clients/destination_test.go, clients/source.go, clients/source_test.go, internal/servers/destinations.go, serve/destination.go, serve/destination_test.go, serve/source.go, serve/source_test.go
Found a nasty hang when context was cancelled. Still need to add some tests for that to catch regression.
=> fix: Exit gracefully on context cancelled

internal/servers/destinations.go
=> fix: Bug where first resource wasn't insert into DB

clients/destination.go
The waitgroup here should defer before being marked as done. Spotted this while looking through the code, but this wasn't causing any serious issues as far as I'm aware though.
=> fix: Add missing defer

.github/workflows/issue_to_project.yml
Same as https://github.com/cloudquery/cloudquery/pull/2693
---
=> chore: Add Issue to public roadmap project

go.mod, go.sum, plugins/source_testing.go, schema/column_test.go
Something like https://github.com/cloudquery/cloudquery/pull/2788 but in the sdk.
=> fix(tests): Parallel plugin testing, remove old faker

cqtypes/timestamptz.go, cqtypes/timestamptz_test.go
=> fix: Parsing timestamptz default string

codegen/table.go, codegen/table_test.go
Add sanity check to `TableDefinition` (#299)
=> feat(codegen): Add sanity check to `TableDefinition`

plugins/destination_memdb_plugin.go, plugins/source_scheduler_dfs.go, plugins/source_validate.go, schema/table.go
Fixes https://github.com/cloudquery/cloudquery/issues/4489, and we'll need to update all dest plugins to use `GetAll`.
We could also pass an option to `Get`.
Maybe leave this open so others can review too
---
=> fix: Allow searching relations by name

plugins/destination_memdb_plugin.go, plugins/destination_test.go, serve/source_test.go
More tests for source and destination plugins with non-happy flow case, context cancellation and other fun stuff.
=> test: Add more non-happy flow tests

schema/cidr.go, schema/inet.go, schema/inet_test.go
Fix nasty bug triggered by Go bug
https://github.com/golang/go/issues/35727
@shimonp21  can you please confirm this solves the bug triggered by the k8s cidr plugin.
=> fix: Workaround Go Inet marshal bug

plugins/source.go, plugins/source_scheduler_dfs.go
Im not sure how we didn't hit this before but I was able to hit this while working on azure number of times. Prob will need another set of eye to make sure it's good now.
=> fix: Concurrent read,write to a map

plugins/source_scheduler_dfs.go
Follow up on https://github.com/cloudquery/plugin-sdk/pull/467#discussion_r1041911547
---
=> fix: Skip relations when initializing metrics

schema/json.go, schema/json_test.go
Continuation of the work here https://github.com/cloudquery/plugin-sdk/pull/479/files
=> fix: Validate json strings and handle empty strings

specs/spec_reader.go, specs/spec_reader_test.go
Closes https://github.com/cloudquery/plugin-sdk/issues/289
=> fix: Throw error on empty env variable

schema/json.go, schema/json_test.go
So we support more types like arrays, strings, etc.
---
=> fix: Use json.Valid

schema/json.go
=> fix: Don't print value with error on invalid JSON

plugins/destination/plugin.go, plugins/destination/plugin_test.go, serve/destination_test.go
Follow up to https://github.com/cloudquery/plugin-sdk/pull/516
---
=> fix(destination): Rename `NewDestinationPlugin` to `NewPlugin`

internal/servers/destinations.go
Closes https://github.com/cloudquery/plugin-sdk/pull/512/files
Closes https://github.com/cloudquery/plugin-sdk/pull/463/files
=> fix: Don't hide errors in destination server

.github/workflows/lint_golang.yml, .github/workflows/lint_markdown.yml, .github/workflows/release-pr.yml
This aligns the SDK CI with other repositories
---
=> chore: Clean up CI

.github/workflows/lint_markdown.yml
Snapshots are now under `plugins/source`
---
=> chore: Fix Vale ignore path

plugins/destination/plugin_testing.go
Extracted from https://github.com/cloudquery/plugin-sdk/pull/542 to allow us to fix https://github.com/cloudquery/cloudquery/issues/6069
Before this change, running cockroachDB tests:
```
Jan  2 11:03:08.760000 INF Query args=["testAppendSource474bca19-69ba-4a5a-8af0-3d890198a243"] commandTag="SELECT 2" module=pgx pid=1570743 sql="SELECT * FROM \"cq_test_write_append\" WHERE _cq_source_name = $1 order by _cq_sync_time asc"
--- FAIL: TestPgPlugin (0.36s)
--- FAIL: TestPgPlugin/TestWriteOverwrite (0.22s)
client_test.go:20: expected first resource diff: value at 2 is(d1ebd2a374f14556852c4d5b23608201) TypeUUID while other is(3da5b2eafc814ecb973bcee770bb70e1) TypeUUID
value at 3 is(d03dd7f8781a4dbb93aaebefb6aaba87) TypeUUID while other is(f16b7d3a0f85441daf30da5d2d8afb26) TypeUUID
value at 7 …
```
=> fix(testing): Sort results before comparison in tests

plugins/destination/plugin_testing.go
There was an issue with append-only tests that only wrote 1 resource: the sort order meant that the incorrect resource was sometimes being compared in this case. 
This PR changes the sort order to be by sync time first, then UUID. Some other tests had to be adapted to work with this new ordering as well.
=> fix(testing): Some fixes to the ordering for plugin tests

transformers/struct.go
Needed for https://github.com/cloudquery/cloudquery/blob/f5a050018ab77303ce5e418bc981a27279cc47ca/plugins/source/gcp/codegen/main.go#L249
---
=> feat(transformers): Add WithTypeTransformer

transformers/struct.go
Some fields in GCP are not mockable as they use internal types we can't recreate in our tests.
See https://github.com/cloudquery/cloudquery/blob/876cc163d6dff277bb09a5147162a8646fcd98de/plugins/source/gcp/codegen/recipes/aiplatform.go#L21
---
=> feat: Add WithIgnoreInTestsTransformer

specs/destination.go, specs/destination_test.go, specs/migrate_mode.go, specs/migrate_mode_test.go, specs/write_mode.go, specs/write_mode_test.go
Related to https://github.com/cloudquery/cloudquery/issues/6600, needed for https://github.com/cloudquery/cloudquery/pull/6763
---
=> feat(destinations): Add `migrate_mode`

.github/workflows/unittest.yml
Trying to add codecov, if it doesn't work directly we might need to do this post the unit tests as in:
https://github.com/cloudquery/plugin-sdk/blob/7d569aaf6516594bb6dc0ca7b49f32fbbef9c6e0/.github/workflows/unittest-post.yml
---
=> chore(ci): Add codecov

registry/download.go
So the error is visible in the console
---
=> feat: Return error message when download fails

schema/text.go, schema/types.go, testdata/testdata.go
Closes https://github.com/cloudquery/cloudquery/issues/5255 after we upgrade the sdk's in the dest-plugins
---
=> test: Add null-in-text-field test

schema/column.go, schema/meta.go
Fixes https://github.com/cloudquery/plugin-sdk/issues/701
---
=> feat(schema): Add Unique column option, set it for CqID

specs/spec_reader.go, specs/spec_reader_test.go
Related to https://github.com/cloudquery/cloudquery/issues/7165. This will require a minor code change to the CLI to call `GetDestinationByName` [here](https://github.com/cloudquery/cloudquery/blob/d75df29d468a84724229ecef6ce558d31e665707/cli/cmd/migrate.go#L56) and [here](https://github.com/cloudquery/cloudquery/blob/d75df29d468a84724229ecef6ce558d31e665707/cli/cmd/sync.go#L70)
---
=> feat(spec): Return sources, destinations in order

clients/source/v1/source.go, cloudquery/source/v1/source.proto, internal/pb/source/v1/source.pb.go, internal/pb/source/v1/source_grpc.pb.go, internal/servers/source/v1/source.go
Part of https://github.com/cloudquery/cloudquery/issues/8731.
Opening for feedback. I added some backwards compatibility code so users don't need to update to the latest plugins versions for this support (we can also drop the new RPC if that makes sense).
Goes with https://github.com/cloudquery/cloudquery/pull/8803
---
=> feat(source): Expose docs generation

CHANGELOG.md, internal/memdb/memdb_test.go, plugins/destination/plugin.go, plugins/destination/plugin_test.go, plugins/destination/plugin_testing.go, plugins/destination/plugin_testing_migrate.go, schema/table.go, specs/destination.go, specs/pk_mode.go, specs/pk_mode_test.go
Initial implementation for https://github.com/cloudquery/cloudquery/issues/8811
---
=> feat: Support for User Specifying Primary Key Scheme (default or cq-ids)

types/json.go, types/json_test.go
Necessary for read tests to pass
=> feat: Add JSON UnmarshalOne

types/inet.go, types/json.go, types/mac.go, types/uuid.go
We need this for CSV reading/writing. 
(Note: this PR is to the `feat/arrow_update` branch)
=> feat: Add ValueString methods

go.mod, go.sum, internal/memdb/memdb.go, internal/memdb/memdb_test.go, internal/servers/destination/v0/destinations.go, plugins/destination/managed_writer.go, plugins/destination/plugin.go, plugins/destination/plugin_testing_migrate.go, plugins/destination/plugin_testing_overwrite.go, plugins/destination/plugin_testing_overwrite_delete_stale.go, plugins/destination/plugin_testing_write_append.go, plugins/destination/unmanaged_writer.go, schema/arrow.go, schema/meta.go, schema/schemas.go, schema/table.go, serve/destination_v0_test.go, types/json.go
=> Arrow sqlite

internal/servers/destination/v0/destinations.go, plugins/destination/managed_writer.go, plugins/destination/plugin.go, plugins/destination/plugin_test.go, schema/arrow.go
This is a follow-up on the latest commit because we were adding just the columns without the data to the records so this should solve it by moving it up to the server
=> fix arrow tests

.github/workflows/release-pr.yml
This should allow us to release https://github.com/cloudquery/plugin-sdk/pull/775.
Please note this targets the v1 branch
---
=> feat(ci): Set up releases for v1

plugins/source/plugin_test.go, schema/resource.go
=> fix: Backport deterministic cq_id fix to v1

go.mod, go.sum, internal/servers/destination/v0/destinations.go, plugins/destination/plugin_testing_migrate.go, plugins/destination/plugin_testing_overwrite.go, plugins/destination/plugin_testing_overwrite_delete_stale.go, plugins/destination/plugin_testing_write_append.go, schema/arrow.go, testdata/testdata.go
=> feat: Use ApproxEqual in dest tests

internal/servers/destination/v0/destinations.go
=> fix: Make cq_id unique for backward compat

internal/servers/destination/v0/destinations.go
Fixes - https://github.com/cloudquery/cloudquery/pull/10160
=> fix: Set _cq_id to NotNull in destinations for backward compat

plugins/destination/plugin.go
=> fix: Make cq_id non required on destination

testdata/testdata.go
Required by:
* https://github.com/cloudquery/cloudquery/pull/10166
* https://github.com/cloudquery/cloudquery/pull/10060
=> fix(testdata): Add old style gen testdata

testdata/testdata.go
=> chore(testdata): Deprecation notice

schema/arrow.go, schema/arrow_test.go
Closes https://github.com/cloudquery/cloudquery/issues/10136
=> feat(arrow): Pretty-print field changes

schema/arrow.go
Before this change, only table name was supported as arrow Schema metadata.
=> feat: Add table description to Arrow schema metadata

transformers/struct.go, transformers/struct_test.go
=> fix(transformer): Allow camel-cased json tags

plugins/destination/plugin_testing.go
=> fix: Destination migration testing using incorrect mode

types/uuid.go
Based on https://github.com/apache/arrow/pull/35457 review
=> chore(UUID): Streamline UUID implementation

internal/memdb/memdb.go, plugins/destination/plugin_testing_overwrite.go, plugins/destination/plugin_testing_overwrite_delete_stale.go, plugins/destination/plugin_testing_write_append.go
=> feat(test): Test writing to a child table

types/inet.go
Right now there is an inconsistency in our extensions: Some of them are using `BinaryType` as the underlying storage and some `StringType`.
There is another issue in the parquet reader that seems not to like extensions with `StringType` but we can solve this bug if we want our Extensions to be of `StringType` rather then `BinaryType`.
Right now I changed `Inet` to `BinaryType` as well for consistency but we have a chance to change all of them to `StringType` before we migrate sources without breaking backward compatibility because we didn't send anything over the wire yet - so right it's just an implementation change rather then a breaking change.
=> fix: Inet extension MarshalJSON

go.mod, go.sum, plugins/destination/diff.go, plugins/destination/plugin_testing.go, plugins/destination/plugin_testing_migrate.go, plugins/destination/plugin_testing_overwrite.go, plugins/destination/plugin_testing_overwrite_delete_stale.go, plugins/destination/plugin_testing_write_append.go
Blocked by https://github.com/apache/arrow/pull/35823
Required by https://github.com/cloudquery/cloudquery/pull/11078
=> fix(test): Use `array.WithUnorderedMapKeys`

internal/servers/plugin/v3/plugin.go, plugin/plugin_source.go, scheduler/scheduler.go, scheduler/scheduler_dfs.go, scheduler/scheduler_round_robin.go, scheduler/scheduler_test.go
Set the fields obtained from the protobuf so that they are passed to the plugin Sync call.
=> fix: Set Sync option fields

go.mod, go.sum, internal/clients/state/v3/state.go, internal/memdb/memdb.go, internal/memdb/memdb_test.go, internal/servers/destination/v0/destinations.go, internal/servers/destination/v1/destinations.go, internal/servers/plugin/v3/plugin.go, internal/servers/plugin/v3/plugin_test.go, message/sync_message.go, message/write_message.go, plugin/plugin.go, plugin/plugin_destination.go, plugin/plugin_source.go, plugin/plugin_test.go, plugin/testing_upsert.go, plugin/testing_write_delete.go, plugin/testing_write_insert.go, plugin/testing_write_migrate.go, scheduler/scheduler.go, scheduler/scheduler_test.go, serve/destination_v0_test.go, serve/destination_v1_test.go, serve/plugin_test.go, writers/batch.go, writers/batch_test.go, writers/mixed_batch.go, writers/mixed_batch_test.go
Follow-up https://github.com/cloudquery/plugin-pb-go/pull/41
This also removes WriteOptions because we moved stuff into messages
=> feat: Split sync and write messages

plugin/testing_upsert.go, plugin/testing_write.go, plugin/testing_write_insert.go, schema/testdata.go, schema/testdata_test.go, serve/destination_v1_test.go
There is still more work to do to make the testing function "production" ready because they become quite vital and some of them are public APIs so we need to think how to generalize them correctly so they are testable, expand etc.. but this should be a good start just so we can start releasing some destinations
=> fix: Add back testing for all types

go.mod, go.sum, internal/memdb/memdb.go, internal/servers/destination/v0/destinations.go, internal/servers/destination/v1/destinations.go, internal/servers/plugin/v3/plugin.go, message/write_message.go, plugin/testing_write_delete.go, writers/batchwriter/batchwriter.go, writers/mixedbatchwriter/mixedbatchwriter_test.go
Updated to https://github.com/cloudquery/plugin-pb-go/pull/46
=> fix: Update to plugin-pb v1.5.0

configtype/duration.go, configtype/duration_test.go
`cmp.Diff` doesn't like it otherwise.
=> fix(configtype): Add `Equal()` method to `Duration`

schema/testdata.go
Just add the missing ones. Supercedes https://github.com/cloudquery/plugin-sdk/pull/1057
=> fix(testdata): Add missing column types

message/sync_message.go
Also add `SyncInserts.GetRecords()` for parity with `WriteInserts`
=> fix(naming): Rename `SyncMessages.InsertMessage()` to `SyncMessages.GetInserts()`

scalar/timestamp_test.go
Brings the test from https://github.com/cloudquery/plugin-sdk/pull/986 (fix was included in https://github.com/cloudquery/plugin-sdk/pull/1064)
=> fix(scalar): Test `AppendTime` on TimestampBuilder

plugin/nulls.go, plugin/testing_upsert.go, plugin/testing_write_delete.go, plugin/testing_write_insert.go, plugin/testing_write_migrate.go
=> fix: Handle null-related test options

writers/batchwriter/batchwriter.go
=> fix: Use background ctx in batchwriter worker

go.mod, go.sum, internal/servers/plugin/v3/plugin.go
Goes with https://github.com/cloudquery/plugin-pb-go/pull/62. I'll update the PR once we release a new version of `plugin-pb-go`
---
=> fix: Add `NoConnection` to init request

writers/streamingbatchwriter/streamingbatchwriter.go
Reported in https://github.com/cloudquery/cloudquery/issues/12334
=> fix(streamingbatchwriter): Missing tickerFn on DeleteWorker

plugin/nulls.go, plugin/nulls_test.go
Found in https://github.com/cloudquery/cloudquery/pull/12725
=> fix: Nulls in lists

.github/renovate.json5
To avoid https://github.com/cloudquery/plugin-sdk/pull/1150 being a `fix`
---
=> chore(ci): Mark SDK updates to the example plugin as `chore`

serve/package.go, serve/package_test.go, serve/testdata/message.txt
Adds zip file checksums to the package.json format.
Includes some commits from https://github.com/cloudquery/plugin-sdk/pull/1216 to avoid merge conflicts later.
=> feat: Add Checksums to package.json format

serve/package_test.go, serve/plugin_test.go
Follow up to https://github.com/cloudquery/plugin-sdk/pull/1227
---
=> test: Update tests

plugin/plugin.go
required for https://github.com/cloudquery/cloudquery/pull/13876
=> fix: Enable format assertion for JSON schema

scalar/list.go, scalar/list_test.go
Fixes issues like https://github.com/cloudquery/cloudquery-issues/issues/595
=> fix(scalar): Don't pass typed nils in list values

writers/batchwriter/batchwriter.go, writers/batchwriter/batchwriter_test.go, writers/batchwriter/unimplemented.go, writers/batchwriter/unimplemented_test.go, writers/streamingbatchwriter/streamingbatchwriter.go, writers/streamingbatchwriter/streamingbatchwriter_test.go, writers/streamingbatchwriter/unimplemented.go, writers/streamingbatchwriter/unimplemented_test.go
=> feat: Support DeleteRecord in all writers

internal/servers/plugin/v3/plugin.go
=> fix: Set all fields in `DeleteRecord` message

writers/mixedbatchwriter/mixedbatchwriter.go
=> fix: Batching for mixedbatchwriter

examples/simple_plugin/go.mod, examples/simple_plugin/go.sum, go.mod, go.sum, internal/memdb/memdb.go, serve/package.go, serve/testdata/memdbtables.json
So when we publish plugins to the Hub they include paid tables data
---
=> feat: Include `is_paid` field when creating tables json during package

schema/testdata.go
`UUID` columns now follow the same pattern as all other columns
This could also be considered a `refactor`... I am open to changing it if people want
=> feat: Make UUID in `testdata` always deterministic like all other columns

premium/usage.go
Goes with https://github.com/cloudquery/cloudquery-api-go/pull/109
---
=> feat: Add Sync Run API Token Type

examples/simple_plugin/go.mod, go.mod
Reverts part of https://github.com/cloudquery/plugin-sdk/pull/1520/files
=> chore: Revert toolchain update

serve/package.go
This code is unreachable, so should be removed
=> fix: Remove unreachable code

plugin/testing_write.go, plugin/testing_write_migrate.go
This adds a test for how destinations will handle removing a unique constraint
=> feat: Add destination tests for removing a unique constraint

examples/simple_plugin/go.mod, examples/simple_plugin/go.sum, go.mod, go.sum, internal/servers/plugin/v3/plugin.go, plugin/plugin.go
Depends On: https://github.com/cloudquery/plugin-pb/pull/21
This PR allows plugin clients to expose functionality that depends on the InvocationID
=> feat: Expose InvocationID to Plugin Client

.github/workflows/go_mod_tidy_examples.yml
Needed to re-trigger workflows after the tidy commit
---
=> fix: Use custom token

serve/opentelemetry_test.go
This PR is designed to ensure that we do not upgrade the OTEL packages and create schema incompatibilities by testing the resource creation
=> chore: Add Test for OTEL Resource Creation

.github/.kodiak.toml
So we can have PRs jump the queue
---
=> chore: Add `priority_merge_label` to `.kodiak.toml`

plugin/plugin_package.go
Based on https://github.com/cloudquery/cloudquery/pull/17693 as well as our `gencc.sh` & `gencpp.sh` files.
Reasoning: previously we used GoReleaser to call the `gencc.sh` & `gencpp.sh` scripts to determine the `CC` & `CXX` variables values. Now we have to fill this info manually during packaging.
=> feat: Fill in `CC` and `CXX` environment variables for `package` command

transformers/struct.go, transformers/struct_test.go
Noticed this while opening https://github.com/cloudquery/cloudquery-issues/issues/2116.
---
=> fix: Don't include non exported fields or ignored types in JSON schema

schema/table.go, schema/table_test.go
Follow up to https://github.com/cloudquery/plugin-sdk/pull/1827#discussion_r1696683944
---
=> fix: Handle commas in permissions array

.golangci.yml, internal/servers/destination/v0/schemav2tov3.go
Adds more rules so we can catch bugs, also fixes a possible nil access panic
---
=> chore: Add more govet lint rules

scheduler/queue/worker.go, scheduler/scheduler_dfs.go
This PR aims to add pre-configured logger support for source plugins by pushing it to the resolver context. 
---
=> feat: Add logger to context

plugin/testing_validation.go
Corrects the function name from `ValidateSensitivColumns` to `ValidateSensitiveColumns`
---
=> chore: Correct sensitive columns validation function name

scheduler/scheduler.go, scheduler/scheduler_test.go
Proposed as an alternative to https://github.com/cloudquery/plugin-sdk/pull/2162/files, it simplifies the logic and ensures clients are distributed evenly across shards.
=> feat: Improve shard chunking
